// Command descgen generates auto-desc.gen.json and auto-desc.gen.go from
// cmd/atlas-mcp/server/tools_*.go source files.
//
// Usage:
//
//	go run ./cmd/atlas-mcp/descgen -out cmd/atlas-mcp/auto-desc.gen.json -pkgdir cmd/atlas-mcp/server
//
// The generator:
//  1. Parses all tools_*.go files in the server directory to extract tool
//     descriptions and input schemas via the descgen.Extract() function.
//  2. Writes auto-desc.gen.json (a JSON map of tool name → ToolDesc).
//  3. Writes auto-desc.gen.go (package server) that embeds the JSON as a byte
//     slice and exposes it via autoDescData() for use during mcp.AddTool calls.
//
// Handlers marked with "// gen:manual-override" are excluded.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/kaecer68/atlas-go/cmd/atlas-mcp/internal/descgen"
)

func main() {
	outPath := flag.String("out", "", "path to write auto-desc.gen.json (required)")
	pkgDir := flag.String("pkgdir", "", "path to the server package directory (required)")
	flag.Parse()

	if *outPath == "" || *pkgDir == "" {
		fmt.Fprintf(os.Stderr, "Usage: descgen -out <json path> -pkgdir <server dir>\n")
		os.Exit(2)
	}

	toolsDir := *pkgDir

	result, err := descgen.Extract(toolsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "descgen: extract failed: %v\n", err)
		os.Exit(1)
	}

	if len(result) == 0 {
		fmt.Fprintf(os.Stderr, "descgen: warning: no tools found in %s\n", toolsDir)
	}

	// Write JSON output.
	jsonData, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "descgen: marshal json: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*outPath, jsonData, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "descgen: write json: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("descgen: wrote %d tool descriptors to %s\n", len(result), *outPath)

	// Write Go file.
	goPath := filepath.Join(*pkgDir, "auto-desc.gen.go")
	if err := writeGoFile(goPath, jsonData); err != nil {
		fmt.Fprintf(os.Stderr, "descgen: write go: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("descgen: wrote %s\n", goPath)
}

// writeGoFile writes a Go source file that embeds jsonData as a byte slice.
// The file is generated in package server and exposes autoDescData().
func writeGoFile(path string, jsonData []byte) error {
	var b []byte
	b = append(b, "// Code generated by cmd/atlas-mcp/descgen; DO NOT EDIT.\n"...)
	b = append(b, "// Run: go generate ./cmd/atlas-mcp/...\n"...)
	b = append(b, "\n"...)
	b = append(b, "package server\n"...)
	b = append(b, "\n"...)
	b = append(b, "import \"encoding/json\"\n"...)
	b = append(b, "\n"...)
	b = append(b, "// autoDescJSON is the auto-generated tool description map, embedded as\n"...)
	b = append(b, "// raw JSON bytes produced from cmd/atlas-mcp/server/tools_*.go sources.\n"...)
	b = append(b, "// It maps tool name → {name, description, inputSchema}.\n"...)
	b = append(b, "var autoDescJSON []byte\n"...)
	b = append(b, "\n"...)
	b = append(b, "// autoDescMap caches the parsed map from autoDescJSON.\n"...)
	b = append(b, "var autoDescMap map[string]autoToolDesc\n"...)
	b = append(b, "\n"...)
	b = append(b, "// autoToolDesc mirrors descgen.ToolDesc for JSON unmarshaling.\n"...)
	b = append(b, "type autoToolDesc struct {\n"...)
	b = append(b, "	Name        string          `json:\"name\"`\n"...)
	b = append(b, "	Description string          `json:\"description\"`\n"...)
	b = append(b, "	InputSchema json.RawMessage `json:\"inputSchema\"`\n"...)
	b = append(b, "}\n"...)
	b = append(b, "\n"...)
	b = append(b, "func init() {\n"...)
	b = append(b, "	autoDescJSON = []byte"...)
	// Append the JSON data as a byte literal.
	writeByteSlice(&b, jsonData)
	b = append(b, "\n"...)
	b = append(b, "\tif err := json.Unmarshal(autoDescJSON, &autoDescMap); err != nil {\n"...)
	b = append(b, "		panic(\"auto-desc.gen.json: invalid JSON embedded at build time: \" + err.Error())\n"...)
	b = append(b, "	}\n"...)
	b = append(b, "}\n"...)
	b = append(b, "\n"...)
	b = append(b, "// autoDesc returns the auto-generated descriptor for tool name, or nil.\n"...)
	b = append(b, "func autoDesc(name string) *autoToolDesc {\n"...)
	b = append(b, "	if d, ok := autoDescMap[name]; ok {\n"...)
	b = append(b, "		return &d\n"...)
	b = append(b, "	}\n"...)
	b = append(b, "	return nil\n"...)
	b = append(b, "}\n"...)
	b = append(b, "\n"...)
	b = append(b, "// autoDescKeys returns all auto-generated tool names.\n"...)
	b = append(b, "func autoDescKeys() []string {\n"...)
	b = append(b, "	keys := make([]string, 0, len(autoDescMap))\n"...)
	b = append(b, "	for k := range autoDescMap {\n"...)
	b = append(b, "		keys = append(keys, k)\n"...)
	b = append(b, "	}\n"...)
	b = append(b, "	return keys\n"...)
	b = append(b, "}\n"...)

	formatted, err := format.Source(b)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// writeByteSlice appends a Go byte slice literal for data to buf.
func writeByteSlice(buf *[]byte, data []byte) {
	*buf = append(*buf, "{\n\t\t"...)
	for i, c := range data {
		if i > 0 && i%40 == 0 {
			*buf = append(*buf, "\n\t\t"...)
		}
		*buf = fmt.Appendf(*buf, "0x%02x, ", c)
	}
	*buf = append(*buf, "\n\t}"...)
}
