// Command docsgen generates cmd/atlas-mcp/server/resources_docs.gen.go —
// an embedded snapshot of atlas-go knowledge docs exposed via atlas-mcp
// static resources (atlas://tools/catalog, atlas://reference/*, ...).
//
// Usage (go:generate from cmd/atlas-mcp/server):
//
//	go run ../../cmd/atlas-mcp/docsgen
//
// Why embedded: atlas-mcp runs from arbitrary CWD (Claude Desktop / Cursor /
// Hermes / OpenCode spawn it outside the repo), so os.ReadFile with relative
// docs/ paths breaks (previously atlas://tools/catalog and
// atlas://workflows/catalog failed when started from /tmp). Embedding a
// build-time snapshot removes the CWD dependency.
//
// Drift guard: ci-gate runs `go generate ./...` and fails on diff — editing
// the source docs without regenerating is caught in CI.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
)

// docFiles maps resource key → {repo-relative path, mime}.
// Keys must match resources.go resource URIs after "atlas://".
var docFiles = map[string][2]string{
	"tools/catalog":              {"docs/reference/tool-catalog.md", "text/markdown"},
	"workflows/catalog":          {"docs/reference/workflow-map.md", "text/markdown"},
	"reference/architecture":     {"docs/architecture.md", "text/markdown"},
	"reference/constitution":     {"docs/reference/constitution.md", "text/markdown"},
	"reference/traps":            {"docs/reference/traps.md", "text/markdown"},
	"reference/parameter-system": {"docs/reference/parameter-system.md", "text/markdown"},
	"processes/catalog":          {"docs/reference/processes.yaml", "text/yaml"},
	"docs/map":                   {"docs/documentation-map.md", "text/markdown"},
	"modules/index":              {"internal/AGENTS_INDEX.md", "text/markdown"},
	"modules/maturity":           {"internal/MATURITY.md", "text/markdown"},
}

func main() {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("runtime.Caller failed")
	}
	genDir := filepath.Dir(file) // <repo>/cmd/atlas-mcp/docsgen
	repoRoot := filepath.Clean(filepath.Join(genDir, "..", "..", ".."))
	outPath := filepath.Join(repoRoot, "cmd", "atlas-mcp", "server", "resources_docs.gen.go")

	keys := make([]string, 0, len(docFiles))
	for k := range docFiles {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by cmd/atlas-mcp/docsgen; DO NOT EDIT.
// Run: go generate ./cmd/atlas-mcp/...
//
// embeddedDocs is a build-time snapshot of atlas-go knowledge docs exposed
// via atlas-mcp static resources. It makes the resources independent of the
// process CWD / filesystem. Edit the source docs (docs/, internal/) and run
// ` + "`go generate ./cmd/atlas-mcp/...`" + ` to refresh (ci-gate drift-checks it).
//
// resource key → file content bytes (mime mapping lives in resources.go).

package server

var embeddedDocs = map[string][]byte{
`)
	for _, k := range keys {
		rel, _ := docFiles[k][0], docFiles[k][1]
		path := filepath.Join(repoRoot, filepath.FromSlash(rel))
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "docsgen: read %s: %v\n", rel, err)
			os.Exit(1)
		}
		fmt.Fprintf(&buf, "\t%q: {", k)
		for i, b := range data {
			if i%16 == 0 {
				buf.WriteString("\n\t\t")
			}
			fmt.Fprintf(&buf, "0x%02x, ", b)
		}
		buf.WriteString("\n\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "docsgen: gofmt: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "docsgen: write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("docsgen: wrote %s (%d keys, %d bytes total)\n", outPath, len(keys), buf.Len())
}
