// System maps (.omo/maps/) are regenerated by the pre-commit hook, not go generate.
// To regenerate manually: go run ./cmd/mapgen -gen-all
//
// This file is the only non-test Go file at the module root. The root used to be a
// legacy `package main` (enhanced_experiment_runner.go, retired 2026-08-18 — see
// docs/decisions/2026-08-code-disposition-enhanced-runner.md). It is declared as a
// plain package so `go build ./...` / `go install .` do not try to link a root
// executable; the //go:generate directive above is unaffected by the package name.
//
//go:generate go run ./cmd/gentags
package atlas
