// Command gentags generates field_names.js from domain struct json tags.
//
// Usage: go run ./cmd/gentags
//
// Reads: internal/domain/*.go
// Writes: web/static/js/shared/field_names.js
//
// This eliminates manual synchronization between Go backend structs
// and JavaScript frontend field access — a single source of truth.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	domainDir := "internal/domain"
	outFile := "web/static/js/shared/field_names.js"

	entries, err := os.ReadDir(domainDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read dir: %v\n", err)
		os.Exit(1)
	}

	fset := token.NewFileSet()
	structs := make(map[string][]string)

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(domainDir, e.Name())
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "parse %s: %v\n", path, err)
			continue
		}

		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				var fields []string
				for _, field := range st.Fields.List {
					if field.Tag == nil {
						continue
					}
					tag := field.Tag.Value
					// Extract json tag value: `json:"field_name,omitempty"` -> "field_name"
					jsonName := extractJSONName(tag)
					if jsonName == "" || jsonName == "-" || len(field.Names) == 0 {
						continue
					}
					fields = append(fields, jsonName)
				}
				if len(fields) > 0 {
					structs[ts.Name.Name] = fields
				}
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Auto-generated by cmd/gentags. DO NOT EDIT.\n")
	b.WriteString("// Run: go run ./cmd/gentags\n")
	b.WriteString("// Source: internal/domain/*.go json tags\n")
	b.WriteString("\n")
	b.WriteString("export const FIELD = {\n")

	names := make([]string, 0, len(structs))
	for name := range structs {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, structName := range names {
		fields := structs[structName]
		b.WriteString(fmt.Sprintf("  %s: {\n", structName))
		for _, field := range fields {
			b.WriteString(fmt.Sprintf("    %s: '%s',\n", field, field))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")

	if err := os.WriteFile(outFile, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Wrote %d structs to %s\n", len(structs), outFile)
}

func extractJSONName(tag string) string {
	tag = strings.Trim(tag, "`")
	idx := strings.Index(tag, `json:"`)
	if idx < 0 {
		return ""
	}
	rest := tag[idx+6:]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return ""
	}
	name := rest[:end]
	if comma := strings.IndexByte(name, ','); comma >= 0 {
		name = name[:comma]
	}
	return name
}
