package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gentags: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	domainDir := "internal/domain"
	outDir := "web/static/js/shared"

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, domainDir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), ".go") && !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return fmt.Errorf("parse domain: %w", err)
	}

	type fieldInfo struct {
		GoName string
		JSON   string
	}
	structs := make(map[string][]fieldInfo)

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}
					if !typeSpec.Name.IsExported() {
						continue
					}
					var fields []fieldInfo
					for _, f := range structType.Fields.List {
						if len(f.Names) == 0 {
							continue
						}
						name := f.Names[0].Name
						if !ast.IsExported(name) {
							continue
						}
						jsonTag := name // fallback
						if f.Tag != nil {
							tag := strings.Trim(f.Tag.Value, "`")
							parts := strings.Fields(tag)
							for _, p := range parts {
								if strings.HasPrefix(p, `json:"`) {
									val := strings.TrimPrefix(p, `json:"`)
									val = strings.TrimSuffix(val, `"`)
									val = strings.Split(val, ",")[0]
									if val != "" && val != "-" {
										jsonTag = val
									}
								}
							}
						}
						// Only include fields with snake_case tags (not pure PascalCase fallbacks)
						if strings.Contains(jsonTag, "_") || jsonTag != name {
							fields = append(fields, fieldInfo{GoName: name, JSON: jsonTag})
						}
					}
					if len(fields) > 0 {
						structs[typeSpec.Name.Name] = fields
					}
				}
			}
		}
	}

	_ = os.MkdirAll(outDir, 0o755)

	var buf bytes.Buffer
	buf.WriteString("// Auto-generated by cmd/gentags. DO NOT EDIT.\n")
	buf.WriteString("// Run: go run ./cmd/gentags\n")
	buf.WriteString("// Source: internal/domain/*.go json tags\n\n")
	buf.WriteString("export const FIELD = {\n")

	names := make([]string, 0, len(structs))
	for n := range structs {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, structName := range names {
		fields := structs[structName]
		buf.WriteString(fmt.Sprintf("  %s: {\n", structName))
		for _, f := range fields {
			buf.WriteString(fmt.Sprintf("    %s: '%s',\n", f.JSON, f.JSON))
		}
		buf.WriteString("  },\n")
	}
	buf.WriteString("};\n")

	jsPath := filepath.Join(outDir, "field_names.js")
	if err := os.WriteFile(jsPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", jsPath, err)
	}

	fmt.Printf("gentags: wrote %s (%d structs)\n", jsPath, len(structs))
	return nil
}
