// File: cmd/backtest-event-flow/main.go
// Package: main
//
// Stage 4 PR#3 — prediction backtest engine.
//
// Reads the 4 staging JSONL files produced by cmd/atlas-stage4-backfill
// (PR#1), reconstructs what the event-driven capital flow predictor
// WOULD have output on each historical trading day, and writes the
// (predicted, actual) pair to SQLite prediction_backtest so that
// PR#4 (template hit_rate recalculation) has statistically meaningful
// sample sizes.
//
// Design notes:
//   - The predictor wiring (calendar / capitalFlow / narrativeModels) is
//     replicated in-process for each historical date. refreshEvents +
//     annual rules give us the deterministic inputs the predictor would
//     have seen at runtime.
//   - The "actual" outcome for each date is taken from
//     prediction_actual_90d.jsonl (PR#1's aggregated realized market
//     returns). Where that file lacks a row (e.g. outage days) we fall
//     back to regime label as a coarse proxy and skip hit/miss scoring.
//   - All rows are stamped is_synthetic=1 because they were generated by
//     re-running a model after-the-fact. No live data is overwritten.
//
// CLI:
//
//	-db       string   SQLite path (default ./data/state/atlas.db)
//	-staging  string   staging JSONL dir (default ./data/staging)
//	-since    string   inclusive start date YYYY-MM-DD
//	-until    string   inclusive end date YYYY-MM-DD
//	-model    string   model_version tag (default "stage4-v1")
//	-dry-run  bool     parse and run predictor but skip SQLite writes
//	-init-schema bool   run ledger.InitSchema before ingesting
package main

import (
	"bufio"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/kaecer68/atlas-go/internal/capitalflow"
	"github.com/kaecer68/atlas-go/internal/eventdriven"
	"github.com/kaecer68/atlas-go/internal/industry"
	"github.com/kaecer68/atlas-go/internal/ledger"
)

// RunOptions groups CLI inputs for a single backtest run. Tests build
// synthesized RunOptions and invoke Run directly.
type RunOptions struct {
	StagingDir string
	DBPath     string
	Since      string
	Until      string
	Model      string
	Now        time.Time
	DryRun     bool
	InitSchema bool
	Logger     *log.Logger
}

// RunStats reports per-run counters. Surfaced in CLI output and used
// by tests for assertions.
type RunStats struct {
	DaysProcessed              int
	DaysSkipped                int
	PredictionsWritten         int
	PredictionsSkippedNoActual int
	Malformed                  int
}

// LoadResult groups staging files in memory after parsing.
type LoadResult struct {
	regimes map[string]regimeRow
	events  map[string][]industry.CalendarEvent
	stress  map[string]stressRow
	actuals map[string]actualRow
}

type regimeRow struct {
	Date       string `json:"date"`
	Regime     string `json:"regime"`
	RecordedAt string `json:"recorded_at"`
}

type stressRow struct {
	Date   string  `json:"date"`
	Score  float64 `json:"score"`
	Source string  `json:"source"`
}

type actualRow struct {
	Date                   string  `json:"date"`
	HitOutcomesCount       int     `json:"hit_outcomes_count"`
	TotalOutcomes          int     `json:"total_outcomes"`
	WinRate                float64 `json:"win_rate"`
	MeanForwardReturn      float64 `json:"mean_forward_return"`
	CapitalFlowChangeProxy float64 `json:"capital_flow_change_proxy"`
}

// Run executes the prediction backtest end-to-end.
func Run(opts RunOptions) (RunStats, error) {
	stats := RunStats{}
	if opts.Logger == nil {
		opts.Logger = log.New(io.Discard, "", 0)
	}
	if opts.Now.IsZero() {
		opts.Now = time.Now().UTC()
	}
	if opts.Model == "" {
		opts.Model = "stage4-v1"
	}
	if err := validateRun(opts); err != nil {
		return stats, err
	}
	if filepath.Dir(opts.DBPath) != "." && filepath.Dir(opts.DBPath) != "" {
		if err := os.MkdirAll(filepath.Dir(opts.DBPath), 0o755); err != nil {
			return stats, fmt.Errorf("mkdir db dir: %w", err)
		}
	}

	loaded, err := loadStaging(opts)
	if err != nil {
		return stats, fmt.Errorf("load staging: %w", err)
	}
	if len(loaded.regimes) == 0 {
		opts.Logger.Printf("no regime rows in staging; nothing to backtest")
		return stats, nil
	}

	opts.Logger.Printf("loaded staging: regime=%d events=%d stress=%d actual=%d",
		len(loaded.regimes), countEvents(loaded.events), len(loaded.stress), len(loaded.actuals))

	// Build sorted unique date list — drives deterministic, replayable
	// iteration order regardless of map randomization.
	allDates := sortedDates(loaded.regimes)

	if opts.DryRun {
		for _, d := range allDates {
			if !inRange(d, opts.Since, opts.Until) {
				continue
			}
			if _, ok := loaded.actuals[d]; ok {
				stats.PredictionsWritten++
			} else {
				stats.PredictionsSkippedNoActual++
			}
			stats.DaysProcessed++
		}
		return stats, nil
	}

	db, err := ledger.OpenSQLiteDB(opts.DBPath)
	if err != nil {
		return stats, fmt.Errorf("open sqlite: %w", err)
	}
	defer func() { _ = db.Close() }()
	if opts.InitSchema {
		if err := ledger.InitSchema(db); err != nil {
			return stats, fmt.Errorf("init schema: %w", err)
		}
	}
	has, err := ledger.NewSQLiteHistoricalStore(db).HasTables(context.Background())
	if err != nil {
		return stats, fmt.Errorf("check tables: %w", err)
	}
	if !has["prediction_backtest"] || !has["regime_history"] {
		return stats, fmt.Errorf("missing prediction_backtest or regime_history in %s; pass -init-schema", opts.DBPath)
	}
	store := ledger.NewSQLiteHistoricalStore(db)

	for _, d := range allDates {
		if !inRange(d, opts.Since, opts.Until) {
			stats.DaysSkipped++
			continue
		}

		row, skipReason := buildBacktestRow(opts, d, loaded)
		if skipReason != "" {
			stats.DaysSkipped++
			stats.PredictionsSkippedNoActual++
			opts.Logger.Printf("skip %s: %s", d, skipReason)
			continue
		}

		if err := store.UpsertPredictionBacktest(context.Background(), row); err != nil {
			return stats, fmt.Errorf("upsert %s: %w", d, err)
		}
		stats.DaysProcessed++
		stats.PredictionsWritten++
	}
	return stats, nil
}

// buildBacktestRow assembles a (predicted, actual, hit) row for a single
// historical date. Returns skipReason non-empty when the row cannot be
// safely built (e.g. no actual outcome for that day).
func buildBacktestRow(opts RunOptions, date string, loaded *LoadResult) (ledger.PredictionBacktestRow, string) {
	r, ok := loaded.regimes[date]
	if !ok {
		return ledger.PredictionBacktestRow{}, "missing regime"
	}
	t, err := time.Parse("2006-01-02", date)
	if err != nil {
		return ledger.PredictionBacktestRow{}, "bad date: " + err.Error()
	}

	stress, hasStress := loaded.stress[date]
	score := deriveCapitalFlowScore(stress, hasStress)
	cal := industry.NewEventCalendar()
	cal.RefreshEvents(t)
	pred := eventdriven.NewPredictor(cal)
	pred.SetCapitalFlow(&staticCF{score: score, label: labelForScore(score)})

	report := pred.Predict(t)
	if len(report.Predictions) == 0 {
		return ledger.PredictionBacktestRow{}, "predictor returned no rows"
	}
	first := report.Predictions[0]

	actual, ok := loaded.actuals[date]
	if !ok || actual.TotalOutcomes == 0 {
		// Coarse fallback: derive from regime label so the row still has a
		// direction for downstream filtering. Hit scoring returns false.
		actualDir, actualFlow := deriveFromRegime(r.Regime)
		return ledger.PredictionBacktestRow{
			Date:                  date,
			PredictedDirection:    first.Direction,
			PredictedConfidence:   first.Confidence,
			ActualDirection:       actualDir,
			ActualCapitalFlowChan: actualFlow,
			Hit:                   false,
			ModelVersion:          opts.Model,
			CapturedAt:            opts.Now,
			IsSynthetic:           1,
		}, ""
	}

	predictedDir := normalizeDir(first.Direction)
	actualDir := normalizeDir(directionFromReturn(actual.CapitalFlowChangeProxy))
	hit := false
	if predictedDir == "neutral" || actualDir == "neutral" {
		hit = false
	} else {
		hit = predictedDir == actualDir
	}

	return ledger.PredictionBacktestRow{
		Date:                  date,
		PredictedDirection:    predictedDir,
		PredictedConfidence:   first.Confidence,
		ActualDirection:       actualDir,
		ActualCapitalFlowChan: actual.CapitalFlowChangeProxy,
		Hit:                   hit,
		ModelVersion:          opts.Model,
		CapturedAt:            opts.Now,
		IsSynthetic:           1,
	}, ""
}

func deriveCapitalFlowScore(s stressRow, ok bool) float64 {
	if !ok {
		return 0
	}
	if s.Score == 0 {
		return 0
	}
	return clampScore(s.Score * 0.1)
}

func labelForScore(s float64) string {
	switch {
	case s > 0.2:
		return "inflow"
	case s < -0.2:
		return "outflow"
	default:
		return "neutral"
	}
}

func normalizeDir(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	switch s {
	case "inflow", "bullish", "up", "positive":
		return "inflow"
	case "outflow", "bearish", "down", "negative":
		return "outflow"
	default:
		return "neutral"
	}
}

func directionFromReturn(r float64) string {
	switch {
	case r > 0.005:
		return "inflow"
	case r < -0.005:
		return "outflow"
	default:
		return "neutral"
	}
}

func deriveFromRegime(regime string) (string, float64) {
	switch strings.ToUpper(strings.TrimSpace(regime)) {
	case "RISK_ON":
		return "inflow", 0.02
	case "RISK_OFF":
		return "outflow", -0.02
	default:
		return "neutral", 0
	}
}

func clampScore(s float64) float64 {
	if s > 1 {
		return 1
	}
	if s < -1 {
		return -1
	}
	return s
}

// ------------------------------------------------------------------
// Staging file loaders.
// ------------------------------------------------------------------

func loadStaging(opts RunOptions) (*LoadResult, error) {
	out := &LoadResult{
		regimes: map[string]regimeRow{},
		events:  map[string][]industry.CalendarEvent{},
		stress:  map[string]stressRow{},
		actuals: map[string]actualRow{},
	}
	for name, target := range map[string]struct {
		path string
		load func(string) error
	}{
		"regime_history_90d.jsonl": {
			path: filepath.Join(opts.StagingDir, "regime_history_90d.jsonl"),
			load: func(p string) error {
				return loadJSONL(p, func(line []byte) error {
					var r regimeRow
					if err := json.Unmarshal(line, &r); err != nil {
						return err
					}
					out.regimes[r.Date] = r
					return nil
				})
			},
		},
		"event_calendar_90d.jsonl": {
			path: filepath.Join(opts.StagingDir, "event_calendar_90d.jsonl"),
			load: func(p string) error {
				return loadJSONL(p, func(line []byte) error {
					var r struct {
						Date         string   `json:"date"`
						EventIDs     []string `json:"event_ids"`
						ActiveThemes []string `json:"active_themes"`
					}
					if err := json.Unmarshal(line, &r); err != nil {
						return err
					}
					t, _ := time.Parse("2006-01-02", r.Date)
					for i, eid := range r.EventIDs {
						theme := ""
						if i < len(r.ActiveThemes) {
							theme = r.ActiveThemes[i]
						}
						out.events[r.Date] = append(out.events[r.Date], industry.CalendarEvent{
							ID:         eid,
							Name:       eid,
							EventType:  theme,
							Direction:  "neutral",
							BaseWeight: 0.5,
							StartDate:  t,
							EndDate:    t.Add(24 * time.Hour),
						})
					}
					return nil
				})
			},
		},
		"stress_index_history_90d.jsonl": {
			path: filepath.Join(opts.StagingDir, "stress_index_history_90d.jsonl"),
			load: func(p string) error {
				return loadJSONL(p, func(line []byte) error {
					var r stressRow
					if err := json.Unmarshal(line, &r); err != nil {
						return err
					}
					out.stress[r.Date] = r
					return nil
				})
			},
		},
		"prediction_actual_90d.jsonl": {
			path: filepath.Join(opts.StagingDir, "prediction_actual_90d.jsonl"),
			load: func(p string) error {
				return loadJSONL(p, func(line []byte) error {
					var r actualRow
					if err := json.Unmarshal(line, &r); err != nil {
						return err
					}
					out.actuals[r.Date] = r
					return nil
				})
			},
		},
	} {
		if err := target.load(target.path); err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
	}
	return out, nil
}

func loadJSONL(path string, each func([]byte) error) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1<<16), 1<<20)
	for scanner.Scan() {
		line := bytesTrim(scanner.Bytes())
		if len(line) == 0 {
			continue
		}
		if err := each(line); err != nil {
			return err
		}
	}
	return scanner.Err()
}

func bytesTrim(b []byte) []byte {
	for len(b) > 0 && (b[0] == ' ' || b[0] == '\t' || b[0] == '\r' || b[0] == '\n') {
		b = b[1:]
	}
	for len(b) > 0 && (b[len(b)-1] == ' ' || b[len(b)-1] == '\t' || b[len(b)-1] == '\r' || b[len(b)-1] == '\n') {
		b = b[:len(b)-1]
	}
	return b
}

func sortedDates(m map[string]regimeRow) []string {
	out := make([]string, 0, len(m))
	for d := range m {
		out = append(out, d)
	}
	sort.Strings(out)
	return out
}

func countEvents(m map[string][]industry.CalendarEvent) int {
	n := 0
	for _, v := range m {
		n += len(v)
	}
	return n
}

// inRange is shared with cmd/atlas-stage4-loader — duplicated to keep
// packages self-contained and avoid a cycle.
func inRange(date, since, until string) bool {
	if date == "" {
		return false
	}
	if since != "" && date < since {
		return false
	}
	if until != "" && date > until {
		return false
	}
	return true
}

// ------------------------------------------------------------------
// CapitalFlowProvider stub for backtest.
// ------------------------------------------------------------------

type staticCF struct {
	score float64
	label string
}

func (s *staticCF) QualityScore() float64 { return s.score }
func (s *staticCF) QualityLabel() string  { return s.label }
func (s *staticCF) LatestAssessment(context.Context) (capitalflow.CapitalFlowAssessment, error) {
	// Backtest scores are explicit replay inputs rather than live, uncalibrated
	// observations; mark the fixture eligible to preserve historical behavior.
	return capitalflow.CapitalFlowAssessment{
		CalibrationStatus: capitalflow.CalibrationEligible,
	}, nil
}

// ------------------------------------------------------------------
// CLI parsing and entry.
// ------------------------------------------------------------------

func parseFlags(args []string) (RunOptions, error) {
	fs := flag.NewFlagSet("backtest-event-flow", flag.ContinueOnError)
	staging := fs.String("staging", "./data/staging", "staging JSONL directory")
	db := fs.String("db", "./data/state/atlas.db", "SQLite database path")
	since := fs.String("since", "", "inclusive lower date YYYY-MM-DD")
	until := fs.String("until", "", "inclusive upper date YYYY-MM-DD")
	model := fs.String("model", "stage4-v1", "model_version tag written to prediction_backtest.model_version")
	dry := fs.Bool("dry-run", false, "parse and score but do not write to SQLite")
	initSchema := fs.Bool("init-schema", false, "run ledger.InitSchema before ingesting")
	if err := fs.Parse(args); err != nil {
		return RunOptions{}, err
	}
	return RunOptions{
		StagingDir: *staging,
		DBPath:     *db,
		Since:      *since,
		Until:      *until,
		Model:      *model,
		DryRun:     *dry,
		InitSchema: *initSchema,
		Now:        time.Now().UTC(),
	}, nil
}

func validateRun(opts RunOptions) error {
	if opts.StagingDir == "" {
		return fmt.Errorf("-staging is required")
	}
	if opts.DBPath == "" {
		return fmt.Errorf("-db is required")
	}
	if opts.Since != "" {
		if _, err := time.Parse("2006-01-02", opts.Since); err != nil {
			return fmt.Errorf("bad -since %q: %w", opts.Since, err)
		}
	}
	if opts.Until != "" {
		if _, err := time.Parse("2006-01-02", opts.Until); err != nil {
			return fmt.Errorf("bad -until %q: %w", opts.Until, err)
		}
	}
	if opts.Since != "" && opts.Until != "" && opts.Since > opts.Until {
		return fmt.Errorf("-since %q is after -until %q", opts.Since, opts.Until)
	}
	return nil
}

func main() {
	opts, err := parseFlags(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		usage(os.Stderr)
		os.Exit(2)
	}
	opts.Logger = log.New(os.Stderr, "", log.LstdFlags)
	stats, err := Run(opts)
	if err != nil {
		fmt.Fprintf(os.Stderr, "backtest failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Backtest complete\n")
	fmt.Printf("  Days processed:        %d\n", stats.DaysProcessed)
	fmt.Printf("  Days skipped:          %d\n", stats.DaysSkipped)
	fmt.Printf("  Predictions written:   %d\n", stats.PredictionsWritten)
	fmt.Printf("  Skipped (no actual):   %d\n", stats.PredictionsSkippedNoActual)
	fmt.Printf("  Malformed rows:        %d\n", stats.Malformed)
}

func usage(w io.Writer) {
	_, _ = fmt.Fprintf(w, "usage: backtest-event-flow -staging DIR [-since YYYY-MM-DD] [-until YYYY-MM-DD] -db PATH\n")
}
