package dailyreport

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/kaecer68/atlas-go/internal/config"
	"github.com/kaecer68/atlas-go/internal/domain"
)

// Report is a daily market report.
type Report struct {
	Date      string          `json:"date"`
	Generated time.Time       `json:"generated_at"`
	Summary   string          `json:"summary"` // mirrored from Global.Summary for frontend convenience
	Global    GlobalOverview  `json:"global"`
	Capital   CapitalSection  `json:"capital"`
	Events    EventsSection   `json:"events"`
	Strategy  StrategySection `json:"strategy"`
	Risk      RiskSection     `json:"risk"`
	Period    *PeriodSection  `json:"period,omitempty"`

	// Workflow state (stateful report lifecycle, 2026-08-23). All fields are
	// omitempty so legacy persisted reports stay byte-compatible. Empty
	// WorkflowStatus means "generated before the workflow feature" and is
	// treated as WorkflowGenerated by the state machine.
	WorkflowStatus  string          `json:"workflow_status,omitempty"`
	RevisedAt       time.Time       `json:"revised_at,omitzero"`
	RevisedBy       string          `json:"revised_by,omitempty"`
	RevisionNote    string          `json:"revision_note,omitempty"`
	RevisionHistory []RevisionEntry `json:"revision_history,omitempty"`
}

type PeriodSection struct {
	MarketPeriod      string                 `json:"market_period"`
	PeriodNameZH      string                 `json:"period_name_zh"`
	CashReserve       float64                `json:"cash_reserve"`
	AllowedStrategies []string               `json:"allowed_strategies"`
	StrategiesDetail  []config.StrategyBrief `json:"strategies_detail,omitempty"`
	Confidence        float64                `json:"confidence"`
	ConditionsHit     int                    `json:"conditions_hit"`
	ConditionsTotal   int                    `json:"conditions_total"`
	// TriggeredIndicators lists each condition evaluated, including unavailable inputs.
	TriggeredIndicators []IndicatorHit `json:"triggered_indicators,omitempty"`
}

// IndicatorHit records the outcome of a single period-detection condition.
// Mirrors portfolio.TriggeredIndicator at the report DTO layer.
type IndicatorHit struct {
	Name           string  `json:"name"`
	Value          float64 `json:"value"`
	Threshold      float64 `json:"threshold"`
	Relation       string  `json:"relation"`
	Hit            bool    `json:"hit"`
	InputAvailable bool    `json:"input_available"`
}

type GlobalOverview struct {
	BondYield string `json:"bond_yield"`
	USDIndex  string `json:"usd_index"`
	JPY       string `json:"jpy"`
	VIX       string `json:"vix"`
	Status    string `json:"status"`
	Summary   string `json:"summary"`
}

type CapitalSection struct {
	Foreign            string  `json:"foreign"`
	ForeignValue       float64 `json:"foreign_value,omitempty"`
	Institutional      string  `json:"institutional"`
	InstitutionalValue float64 `json:"institutional_value,omitempty"`
	Dealer             string  `json:"dealer"`
	DealerValue        float64 `json:"dealer_value,omitempty"`
	Government         string  `json:"government"`
	GovernmentValue    float64 `json:"government_value,omitempty"`
	Retail             string  `json:"retail"`
	RetailValue        float64 `json:"retail_value,omitempty"`
	Resonance          float64 `json:"resonance"`
	Quality            string  `json:"quality"`
}

type EventsSection struct {
	Tomorrow []string `json:"tomorrow"`
	ThisWeek []string `json:"this_week"`
	Count    int      `json:"count"`
}

type StrategySection struct {
	Active    string `json:"active_strategy"`
	EntryCond string `json:"entry_condition"`
	Direction string `json:"direction"`
}

type RiskSection struct {
	StressIndex   float64 `json:"stress_index"`
	DrawdownAlert bool    `json:"drawdown_alert"`
	RiskLevel     string  `json:"risk_level"`
	Warning       string  `json:"warning,omitempty"`
}

// ---------- Data providers ------------------------------------------------

// MacroDataProvider feeds global macro snapshot data.
type DataProvider interface {
	FetchMacro() (GlobalOverview, error)
	FetchCapital() (CapitalSection, error)
	FetchEvents(now time.Time) (EventsSection, error)
}

// Generator produces daily reports.
type Generator struct {
	mu             sync.RWMutex
	latest         *Report
	archive        map[string]*Report
	workDir        string
	provider       DataProvider
	regimeGetter   func() domain.Regime
	periodProvider PeriodProvider
	tracker        *Tracker
}

// PeriodInfo carries the seven-period classification for a daily report.
type PeriodInfo struct {
	MarketPeriod        string
	PeriodNameZH        string
	CashLevel           float64
	AllowedStrategies   []string
	StrategiesDetail    []config.StrategyBrief
	Confidence          float64
	ConditionsHit       int
	ConditionsTotal     int
	TriggeredIndicators []IndicatorHit
}

// PeriodProvider returns the current period section when available.
type PeriodProvider func() *PeriodInfo

// SetPeriodProvider sets a callback that supplies the current seven-period
// classification and its methodology-derived recommendations.
func (g *Generator) SetPeriodProvider(fn PeriodProvider) {
	g.periodProvider = fn
}

// NewGenerator creates a daily report generator.
func NewGenerator(workDir string) *Generator {
	return &Generator{
		workDir:  workDir,
		archive:  make(map[string]*Report),
		provider: &defaultProvider{},
	}
}

// SetProvider sets the data provider for live data.
func (g *Generator) SetProvider(p DataProvider) {
	g.provider = p
}

// SetRegimeProvider sets a callback that returns the current market regime.
// When set, the report's global.Status is overridden with this value so that
// daily_report and system health agree on the same JANUS/local regime.
func (g *Generator) SetRegimeProvider(fn func() domain.Regime) {
	g.regimeGetter = fn
}

// SetTracker attaches the cross-day claim tracker. When set, Generate()
// automatically creates tracked claims (strategy / period / risk) for each
// new report. Nil-safe: the tracker is optional and never blocks generation.
func (g *Generator) SetTracker(t *Tracker) {
	g.tracker = t
}

func (g *Generator) resolveRegime() domain.Regime {
	if g.regimeGetter != nil {
		if r := g.regimeGetter(); r != "" {
			return r
		}
	}
	return domain.RegimeNeutral
}

// summarizeGlobalStatus derives the one-line global summary from the regime
// status so the two fields can never diverge (fix manifest #B06).
func summarizeGlobalStatus(status string) string {
	switch domain.Regime(status) {
	case domain.RegimeRiskOn:
		return "盤勢偏多（RISK_ON）：風險偏好回升，留意外資動向與量價配合"
	case domain.RegimeRiskOff:
		return "盤勢偏空（RISK_OFF）：避險情緒升溫，留意外資流出壓力與波動加劇"
	default:
		return "盤勢中性（NEUTRAL）：方向不明，建議觀望並等待訊號一致"
	}
}

// Generate creates the day's report.
func (g *Generator) Generate() *Report {
	now := time.Now()
	date := now.Format("2006-01-02")

	global, _ := g.provider.FetchMacro()
	global.Status = string(g.resolveRegime())
	// Summary is derived from Status so the report can never contradict
	// itself (previously a hardcoded "偏寬鬆" line sat next to RISK_OFF).
	global.Summary = summarizeGlobalStatus(global.Status)
	capital, _ := g.provider.FetchCapital()
	events, _ := g.provider.FetchEvents(now)

	r := &Report{
		Date:           date,
		Generated:      now,
		Summary:        global.Summary,
		Global:         global,
		Capital:        capital,
		Events:         events,
		WorkflowStatus: WorkflowNeedsReview, // auto-generated reports await human review
		Strategy: StrategySection{
			Active:    "all_weather",
			EntryCond: "等待回測支撐區間",
			Direction: "偏多",
		},
		Risk: RiskSection{
			StressIndex:   0.3,
			DrawdownAlert: false,
			RiskLevel:     "moderate",
		},
	}

	if g.periodProvider != nil {
		if info := g.periodProvider(); info != nil {
			r.Period = &PeriodSection{
				MarketPeriod:        info.MarketPeriod,
				PeriodNameZH:        info.PeriodNameZH,
				CashReserve:         info.CashLevel,
				AllowedStrategies:   info.AllowedStrategies,
				StrategiesDetail:    info.StrategiesDetail,
				Confidence:          info.Confidence,
				ConditionsHit:       info.ConditionsHit,
				ConditionsTotal:     info.ConditionsTotal,
				TriggeredIndicators: info.TriggeredIndicators,
			}
		}
	}

	g.mu.Lock()
	g.latest = r
	g.archive[date] = r
	g.mu.Unlock()

	g.persist(r)
	if g.tracker != nil {
		if err := g.tracker.CreateClaimsFromReport(r); err != nil {
			log.Printf("[DailyReport] create tracked claims: %v", err)
		}
	}
	return r
}

// Markdown renders the report as Markdown.
func (r *Report) Markdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# 台股每日市場報告 — %s\n\n", r.Date)
	fmt.Fprintf(&b, "**生成時間**：%s\n\n", r.Generated.Format("2006-01-02 15:04:05"))

	b.WriteString("## 一、全球資金總開關\n\n")
	fmt.Fprintf(&b, "- 美債殖利率：%s\n", r.Global.BondYield)
	fmt.Fprintf(&b, "- 美元指數：%s\n", r.Global.USDIndex)
	fmt.Fprintf(&b, "- 日圓：%s\n", r.Global.JPY)
	fmt.Fprintf(&b, "- VIX：%s\n", r.Global.VIX)
	fmt.Fprintf(&b, "- 狀態：**%s**\n", r.Global.Status)
	fmt.Fprintf(&b, "- %s\n\n", r.Global.Summary)

	b.WriteString("## 二、台股資金流向\n\n")
	fmt.Fprintf(&b, "- 外資：%s\n", r.Capital.Foreign)
	fmt.Fprintf(&b, "- 投信：%s\n", r.Capital.Institutional)
	fmt.Fprintf(&b, "- 自營商：%s\n", r.Capital.Dealer)
	fmt.Fprintf(&b, "- 公股行庫：%s\n", r.Capital.Government)
	fmt.Fprintf(&b, "- 散戶：%s\n", r.Capital.Retail)
	fmt.Fprintf(&b, "- 共振強度：%.2f\n", r.Capital.Resonance)
	fmt.Fprintf(&b, "- 資金品質：%s\n\n", r.Capital.Quality)

	b.WriteString("## 三、事件日曆\n\n")
	fmt.Fprintf(&b, "- 明天：%s\n", strings.Join(r.Events.Tomorrow, "、"))
	fmt.Fprintf(&b, "- 本週：%s\n\n", strings.Join(r.Events.ThisWeek, "、"))

	b.WriteString("## 四、策略訊號\n\n")
	fmt.Fprintf(&b, "- 推薦策略：%s\n", r.Strategy.Active)
	fmt.Fprintf(&b, "- 進場條件：%s\n", r.Strategy.EntryCond)
	fmt.Fprintf(&b, "- 方向：%s\n\n", r.Strategy.Direction)

	b.WriteString("## 五、風險提示\n\n")
	fmt.Fprintf(&b, "- 壓力指數：%.2f\n", r.Risk.StressIndex)
	fmt.Fprintf(&b, "- 風險等級：%s\n", r.Risk.RiskLevel)
	if r.Risk.Warning != "" {
		fmt.Fprintf(&b, "- ⚠️ %s\n", r.Risk.Warning)
	}

	return b.String()
}

// ---------- Default provider (hard-coded fallback) ------------------------

type defaultProvider struct{}

func (d *defaultProvider) FetchMacro() (GlobalOverview, error) {
	return GlobalOverview{
		BondYield: "4.25%", USDIndex: "104.5", JPY: "150.2", VIX: "14.3",
		Status: "", Summary: "全球資金環境偏寬鬆，有利風險資產",
	}, nil
}

func (d *defaultProvider) FetchCapital() (CapitalSection, error) {
	return CapitalSection{
		Foreign: "偏多", Institutional: "中性", Dealer: "偏多",
		Government: "中性", Retail: "偏空",
		Resonance: 1.0, Quality: "moderate_inflow",
	}, nil
}

func (d *defaultProvider) FetchEvents(_ time.Time) (EventsSection, error) {
	return EventsSection{Tomorrow: []string{"無重大事件"}, ThisWeek: []string{"月營收公告期"}, Count: 1}, nil
}

// ---------- Persist --------------------------------------------------------

func (g *Generator) persist(r *Report) {
	dir := filepath.Join(g.workDir, "data", "reports")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	path := filepath.Join(dir, r.Date+".json")
	f, err := os.Create(path)
	if err != nil {
		return
	}
	defer func() {
		if err := f.Close(); err != nil {
			log.Printf("[DailyReport] close persist file: %v", err)
		}
	}()
	if err := json.NewEncoder(f).Encode(r); err != nil {
		log.Printf("[DailyReport] encode persist: %v", err)
	}
}

// Latest returns the most recent report.
func (g *Generator) Latest() *Report {
	g.mu.RLock()
	defer g.mu.RUnlock()
	return g.latest
}

// GetByDate returns a specific date's report.
func (g *Generator) GetByDate(date string) *Report {
	g.mu.RLock()
	defer g.mu.RUnlock()
	return g.archive[date]
}

// Revise applies a human revision to the report for date, persists the
// corrected version (revision history stays inside the report file) and
// returns the updated report. The corrected report becomes the downstream
// version — it replaces the in-memory archive entry and the on-disk file.
func (g *Generator) Revise(date string, req ReviseRequest) (*Report, error) {
	g.mu.Lock()
	r := g.archive[date]
	if r == nil {
		g.mu.Unlock()
		return nil, fmt.Errorf("%w: %s", errReportNotFound, date)
	}
	if err := r.ApplyRevision(req); err != nil {
		g.mu.Unlock()
		return nil, err
	}
	g.mu.Unlock()

	g.persist(r)
	return r, nil
}

// Approve marks the report for date as approved without revision.
func (g *Generator) Approve(date string) (*Report, error) {
	g.mu.Lock()
	r := g.archive[date]
	if r == nil {
		g.mu.Unlock()
		return nil, fmt.Errorf("%w: %s", errReportNotFound, date)
	}
	if err := r.Approve(); err != nil {
		g.mu.Unlock()
		return nil, err
	}
	g.mu.Unlock()

	g.persist(r)
	return r, nil
}

// ---------- HTTP Handlers -------------------------------------------------

type Handler struct {
	gen     *Generator
	tracker *Tracker
}

func NewHandler(gen *Generator, tracker *Tracker) *Handler {
	return &Handler{gen: gen, tracker: tracker}
}

func (h *Handler) HandleLatest(w http.ResponseWriter, r *http.Request) {
	rep := h.gen.Latest()
	if rep == nil {
		rep = h.gen.Generate()
	}
	format := r.URL.Query().Get("format")
	w.Header().Set("Content-Type", "application/json")
	if format == "markdown" {
		w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
		_, _ = w.Write([]byte(rep.Markdown()))
		return
	}
	if err := json.NewEncoder(w).Encode(rep); err != nil {
		log.Printf("[DailyReport] encode latest: %v", err)
	}
}

func (h *Handler) HandleArchive(w http.ResponseWriter, r *http.Request) {
	date := r.URL.Query().Get("date")
	if date == "" {
		http.Error(w, "?date=YYYY-MM-DD required", http.StatusBadRequest)
		return
	}
	rep := h.gen.GetByDate(date)
	if rep == nil {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(rep); err != nil {
		log.Printf("[DailyReport] encode archive: %v", err)
	}
}

func (h *Handler) HandleSubscribe(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "POST required", http.StatusMethodNotAllowed)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(map[string]string{"status": "subscribed"}); err != nil {
		log.Printf("[DailyReport] encode subscribe: %v", err)
	}
}

// RegisterRoutes installs the /api/reports/* endpoints. tracker may be nil
// (claims endpoints then return 503); the revise/approve endpoints are
// admin-auth guarded (same ATLAS_API_KEY policy as cmd/atlas wrapAdminAuth).
func RegisterRoutes(mux *http.ServeMux, gen *Generator, tracker *Tracker) {
	h := NewHandler(gen, tracker)
	mux.HandleFunc("GET /api/reports/latest", h.HandleLatest)
	// Deprecated: not yet implemented; reserved for v0.0.0.32. See docs/operations/tier-boundary.md.
	mux.HandleFunc("GET /api/reports/archive", h.HandleArchive)
	// Deprecated: not yet implemented; reserved for v0.0.0.32. See docs/operations/tier-boundary.md.
	mux.HandleFunc("POST /api/reports/subscribe", h.HandleSubscribe)

	// Stateful workflow: human-in-the-loop correction (2026-08-23).
	mux.HandleFunc("POST /api/reports/{date}/revise", wrapAdminAuth(h.HandleRevise))
	mux.HandleFunc("POST /api/reports/{date}/approve", wrapAdminAuth(h.HandleApprove))
	// Cross-day claim tracking query.
	mux.HandleFunc("GET /api/reports/tracked-claims", h.HandleTrackedClaims)
}
