// Auto-generated by cmd/gentags. DO NOT EDIT.
// Run: go generate ./...  or  go run ./cmd/gentags
// Source: internal/domain/*.go json tags
//
// Use: import type { GuardOutcome, RecommendationOutcome } from './field_types.js';
//      const item: RecommendationOutcome = apiResponse.items[0];

export interface AlertChannelConfig {
  telegram_bot_token?: string;
  telegram_chat_id?: string;
  email_smtp_host?: string;
  email_smtp_port?: number;
  email_from?: string;
  email_to?: string[];
  email_password?: string;
  webhook_url?: string;
  webhook_headers?: Record<string, string>;
}

export interface AlertRecord {
  id: string;
  timestamp: string;
  rule: string;
  severity: string;
  message: string;
  value: number;
  threshold: number;
  acknowledged: boolean;
  acknowledged_at?: string | null;
  acknowledged_by?: string;
}

export interface BacktestWindowSummary {
  window_id: string;
  start_date: string;
  end_date: string;
  session_count: number;
  outcome_count: number;
  worst_agent_id: string;
  worst_agent_skill: string;
  worst_agent_layer: string;
  worst_agent_window_count: number;
  worst_agent_sharpe_like: number;
  generated_at: string;
}

export interface BaselineHistoryRecord {
  id: string;
  execution_id?: string;
  experiment_id?: string;
  version_before: number;
  version_after: number;
  promoted_by: string;
  promoted_at: string;
  baseline_path: string;
  diff_summary?: string[];
  diff_patch?: string;
  metadata?: string[];
}

export interface BrokerRuntimeAudit {
  mode: string;
  adapter: string;
  signer: string;
  signer_version: string;
  key_id: string;
  max_retries: number;
  http_timeout_sec: number;
  http_attempts: number;
  retry_status_codes: number[];
  max_clock_skew_sec: number;
  nonce_ttl_sec: number;
  nonce_store: string;
  nonce_store_path: string;
  nonce_redis_prefix: string;
}

export interface CapitalPhaseConfig {
  current_phase: string;
  phase_start_date: string;
  min_days_per_phase: number;
  max_drawdown_limit: number;
  sharpe_threshold: number;
  capital_limits: Record<string, number>;
  max_consecutive_losses: number;
}

export interface CapitalSnapshot {
  phase: string;
  phase_start_date: string;
  days_in_phase: number;
  total_capital: number;
  deployed_capital: number;
  reserve_cash: number;
  rolling_sharpe: number;
  max_drawdown: number;
  consecutive_losses: number;
  can_advance: boolean;
  advance_reason?: string;
}

export interface DailyBar {
  date: string;
  symbol: string;
  name: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  source: string;
}

export interface DailySummaryReport {
  date: string;
  sections: string[];
  top_picks: string[];
  risk_level: string;
  narrative_count: number;
}

export interface DayResult {
  date: string;
  regime: string;
  orders: string[];
  positions: string[];
  cash: number;
  portfolio_value: number;
  daily_pnl: number;
}

export interface ExecutionPolicy {
  conviction_floor: number;
  require_cro_pass: boolean;
  momentum_crash_protection: boolean;
  enable_conviction_normalization: boolean;
}

export interface ExperimentLineageRecord {
  experiment_id: string;
  execution_id: string;
  parent_experiment_id?: string;
  root_experiment_id: string;
  lineage_depth: number;
  target_agent_id: string;
  target_skill: string;
  mutation_type: string;
  brief_path?: string;
  candidate_path?: string;
  result_path?: string;
  status: string;
  git_commit_id?: string;
  params_snapshot?: string[];
  result_snapshot?: string[];
  baseline_value?: number | null;
  candidate_value?: number | null;
  improvement_value?: number | null;
  recorded_at: string;
  judged_at?: string | null;
}

export interface MetricTrendPoint {
  id: string;
  execution_id: string;
  experiment_id?: string;
  series_key: string;
  metric_name: string;
  metric_scope: string;
  metric_value: number;
  baseline_value?: number | null;
  delta_value?: number | null;
  sampled_at: string;
  tags?: string[];
}

export interface Position {
  symbol: string;
  quantity: number;
  average_cost: number;
  current_price: number;
  market_value: number;
  unrealized_pnl: number;
}

export interface ReportSection {
  title: string;
  content: string;
  priority: number;
}

export interface RetailSentimentSnapshot {
  margin_balance: number;
  margin_change_pct: number;
  day_trading_ratio: number;
  margin_percentile: number;
  timestamp: string;
}

export interface RiskSnapshot {
  var_95: number;
  var_99: number;
  cvar_95: number;
  max_drawdown_pct: number;
}

export interface SessionSummary {
  session_id: string;
  regime: string;
  order_count: number;
  position_count: number;
  ending_cash: number;
  portfolio_value: number;
  outcome_count: number;
  broker_runtime: string;
  next_experiment_agent_id: string;
  proposal_id: string;
  commit_id: string;
  approval_id: string;
  guard_outcomes: string[];
  recorded_at: string;
  tax_snapshots?: string[];
  after_tax_pnl: number;
  total_tax_paid: number;
}

export interface SimulationConstraints {
  starting_cash: number;
  max_position_weight: number;
  max_open_positions: number;
  min_tradable_volume: number;
  min_recommendation_conviction: number;
  require_cro_pass: boolean;
  transaction_cost_bps: number;
  slippage_bps: number;
  reserve_cash_fraction: number;
  stop_loss_pct: number;
  take_profit_pct: number;
}

export interface SimulationReport {
  total_return: number;
  sharpe_ratio: number;
  max_drawdown: number;
  equity_curve: number[];
  agent_hit_rates: Record<string, number>;
  trade_count: number;
  start_date: string;
  end_date: string;
}

export interface SimulationResult {
  risk_snapshot?: string | null;
  tax_snapshots?: string[];
  before_tax_pnl: number;
  after_tax_pnl: number;
  total_tax_paid: number;
}

export interface SimulationState {
  cash: number;
  positions: string[];
  cumulative_pnl: number;
  equity_curve: number[];
  daily_returns: number[];
  previous_values: Record<string, number>;
  max_equity: number;
  current_drawdown: number;
}

export interface TaskExecution {
  id: string;
  task_type: string;
  command_name: string;
  command_args?: string[];
  request_payload?: string[];
  status: string;
  actor: string;
  actor_source: string;
  idempotency_key?: string;
  retry_of?: string;
  parent_execution_id?: string;
  experiment_id?: string;
  result_path?: string;
  baseline_version_before?: number | null;
  baseline_version_after?: number | null;
  requires_confirmation: boolean;
  confirmed_at?: string | null;
  cancel_requested_at?: string | null;
  submitted_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  exit_code?: number | null;
  error_message?: string;
  summary?: string[];
  created_at: string;
  updated_at: string;
}

export interface TaskExecutionEvent {
  execution_id: string;
  sequence: number;
  event_type: string;
  stream: string;
  level?: string;
  message: string;
  payload?: string[];
  created_at: string;
}

export interface TaxConfig {
  dividend_tax_rate: number;
  transaction_tax_rate: number;
  include_nhi: boolean;
}

export interface TaxSnapshot {
  symbol: string;
  dividend_tax_rate: number;
  transaction_tax_rate: number;
  dividend_tax: number;
  transaction_tax: number;
  total_tax: number;
  after_tax_pnl: number;
}

