// Auto-generated by cmd/gentags. DO NOT EDIT.
// Run: go generate ./...  or  go run ./cmd/gentags
// Source: internal/domain/**/*.go, internal/monitoring/api/**/*.go, internal/monitoring/service/**/*.go

declare interface AgentAttribution {
  agent_id: string;
  agent_name: string;
  layer: string;
  total_return: number;
  count: number;
  avg_return: number;
}

declare interface AgentContribution {
  agent_id: string;
  skill: string;
  layer: string;
  total_return: number;
  win_rate: number;
  trade_count: number;
  avg_return: number;
  sharpe_like: number;
}

declare interface AgentObservatoryResponse {
  session_id: string;
  next_experiment_agent_id: string;
  scorecards: Scorecard[];
  broker_runtime: BrokerRuntimeAudit;
  recorded_at: string;
}

declare interface AgentSpec {
  darwinian_weight?: number;
  screening_criteria: string;
}

declare interface AgentUniverseView {
  agent_id: string;
  name: string;
  layer: string;
  universe: string[];
  screening_criteria: ScreeningCriteria;
}

declare interface AlertBreakdown {
  rule: string;
  description: string;
  current: number;
  threshold: number;
  delta: number;
  formula: string;
}

declare interface AlertChannelConfig {
  telegram_bot_token?: string;
  telegram_chat_id?: string;
  email_smtp_host?: string;
  email_smtp_port?: number;
  email_from?: string;
  email_to?: string[];
  email_password?: string;
  webhook_url?: string;
  webhook_headers?: Record<string, string>;
}

declare interface AlertRecord {
  id: string;
  timestamp: string;
  rule: string;
  severity: string;
  message: string;
  value: number;
  threshold: number;
  breakdown?: string | null;
  acknowledged: boolean;
  acknowledged_at?: string | null;
  acknowledged_by?: string;
}

declare interface BacktestWindowSummary {
  window_id: string;
  start_date: string;
  end_date: string;
  session_count: number;
  outcome_count: number;
  worst_agent_id: string;
  worst_agent_skill: string;
  worst_agent_layer: string;
  worst_agent_window_count: number;
  worst_agent_sharpe_like: number;
  generated_at: string;
}

declare interface BaselineHistoryRecord {
  id: string;
  execution_id?: string;
  experiment_id?: string;
  version_before: number;
  version_after: number;
  promoted_by: string;
  promoted_at: string;
  baseline_path: string;
  diff_summary?: string[];
  diff_patch?: string;
  metadata?: string[];
}

declare interface BenchmarkComparisonResponse {
  snapshot_time: string;
  session_count: number;
  portfolio_return: number;
  taiex_return: number;
  outperformance: number;
  alpha: number;
  beta: number;
  tracking_error: number;
  sharpe_ratio: number;
  info_ratio: number;
  equity_curve: string[];
}

declare interface BenchmarkPoint {
  label: string;
  portfolio: number;
  benchmark: number;
  outperf: number;
}

declare interface BrokerRuntimeAudit {
  mode: string;
  adapter: string;
  signer: string;
  signer_version: string;
  key_id: string;
  max_retries: number;
  http_timeout_sec: number;
  http_attempts: number;
  retry_status_codes: number[];
  max_clock_skew_sec: number;
  nonce_ttl_sec: number;
  nonce_store: string;
  nonce_store_path: string;
  nonce_redis_prefix: string;
}

declare interface CapitalPhaseConfig {
  current_phase: string;
  phase_start_date: string;
  min_days_per_phase: number;
  max_drawdown_limit: number;
  sharpe_threshold: number;
  capital_limits: Record<string, number>;
  max_consecutive_losses: number;
}

declare interface CapitalSnapshot {
  phase: string;
  phase_start_date: string;
  days_in_phase: number;
  total_capital: number;
  deployed_capital: number;
  reserve_cash: number;
  rolling_sharpe: number;
  max_drawdown: number;
  consecutive_losses: number;
  can_advance: boolean;
  advance_reason?: string;
}

declare interface ChannelAlert {
  channel_id: string;
  status: string;
  error: string;
}

declare interface ChannelHealthRecord {
  status: string;
  last_fetch_at: string;
  last_data_at?: string;
  last_error?: string;
  last_success_at?: string;
  rate_limit_remaining?: number;
  latency_ms?: number;
  records_fetched?: number;
  symbols_processed?: number;
  errors?: string[];
}

declare interface CircuitBreakerStateResponse {
  state: string;
  state_changed_at: string;
  consecutive_sl: number;
  cooldown_until: string;
  intraday_peak: number;
  day_start_value: number;
  events: string[];
  initialized: boolean;
}

declare interface CircuitBreakerStatus {
  state: string;
  state_changed_at: string;
  consecutive_sl: number;
  cooldown_until: string;
  intraday_peak: number;
  day_start_value: number;
}

declare interface ConvictionBreakdown {
  base: number;
  floor: number;
  final: number;
  steps: string[];
}

declare interface ConvictionStep {
  rule: string;
  delta: number;
  reason: string;
  source?: string;
  param_ref?: string;
  param_value?: string;
  sensitivity?: number | null;
}

declare interface CorrelationMatrixResponse {
  symbols: string[];
  labels: string[];
  matrix: number[][];
}

declare interface CrossFootCheck {
  is_balanced: boolean;
  portfolio_unrealized: number;
  sum_positions_unrealized: number;
  difference: number;
}

declare interface CyclePosition {
  industry: string;
  name: string;
  business_cycle: string;
  inventory_cycle: string;
  capex_cycle: string;
  confidence: number;
  updated_at: string;
  is_favorable: boolean;
  phase_score: number;
  trend: string;
  confidence_breakdown?: Record<string, number>;
  narrative_theme?: string;
  threshold_evidence?: Record<string, string>;
  evidence: string;
}

declare interface DailyBar {
  date: string;
  symbol: string;
  name: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  source: string;
}

declare interface DailySummaryReport {
  date: string;
  sections: string[];
  top_picks: string[];
  risk_level: string;
  narrative_count: number;
}

declare interface DarwinianAgentInfo {
  weight: number;
  rolling_sharpe: number;
  hit_rate: number;
  total_signals: number;
  win_count: number;
  loss_count: number;
  avg_return: number;
  last_updated?: string;
}

declare interface DarwinianHistoryPoint {
  agent_id: string;
  timestamp: string;
  weight: number;
  rolling_sharpe: number;
  hit_rate: number;
}

declare interface DarwinianStatusData {
  status: string;
  last_computed?: string;
  agent_count: number;
  agents: Record<string, string>;
}

declare interface DataChannel {
  channel_id: string;
  country: string;
  platform: string;
  api_format: string;
  path: string;
  storage: string;
  status: string;
  status_text: string;
  updated_at: string;
  last_error?: string;
}

declare interface DataChannelInfo {
  channel_id: string;
  label: string;
  status: string;
  status_text: string;
  updated_at: string;
}

declare interface DataIntegrityResponse {
  overall: string;
  checks: string[];
  warnings: string[];
}

declare interface DataQualityCheck {
  name: string;
  status: string;
  message: string;
  details?: Record<string, string>;
  checked_at: string;
  duration_ms: string;
}

declare interface DataQualityReport {
  checks: string[];
  overall: string;
  score: number;
  generated_at: string;
}

declare interface DayResult {
  date: string;
  regime: string;
  orders: string[];
  trades: string[];
  positions: string[];
  cash: number;
  portfolio_value: number;
  daily_pnl: number;
  fallback_events?: string[];
}

declare interface DividendRecord {
  symbol: string;
  year: number;
  cash_dividend: number;
  stock_dividend: number;
  ex_dividend_date: string;
  payment_date: string;
}

declare interface EquityCurvePoint {
  label: string;
  value: number;
  currency?: string;
  after_tax_value?: number;
  tax_paid?: number;
}

declare interface EventBlock {
  today: string[];
  recent: string[];
  premarket?: string | null;
}

declare interface ExecutionPolicy {
  conviction_floor: number;
  require_cro_pass: boolean;
  momentum_crash_protection: boolean;
  enable_conviction_normalization: boolean;
}

declare interface ExitAlert {
  symbol: string;
  name: string;
  days_held: number;
  pnl_pct: number;
  suggestion: string;
}

declare interface ExperimentInboxItem {
  experiment_id: string;
  target_agent_id: string;
  skill: string;
  mutation_type: string;
  mutation_summary?: string;
  status: string;
  baseline_value: number;
  candidate_value: number;
  baseline_monetary_ntd?: number;
  candidate_monetary_ntd?: number;
  candidate_path: string;
  reject_reason?: string;
  recorded_at: string;
}

declare interface ExperimentInboxResponse {
  pending_judges: string[];
  pending_promotes: string[];
  recent_history: string[];
  baseline_version: number;
  items: string[];
}

declare interface ExperimentLineageRecord {
  experiment_id: string;
  execution_id: string;
  parent_experiment_id?: string;
  root_experiment_id: string;
  lineage_depth: number;
  target_agent_id: string;
  target_skill: string;
  mutation_type: string;
  brief_path?: string;
  candidate_path?: string;
  result_path?: string;
  status: string;
  git_commit_id?: string;
  params_snapshot?: string[];
  result_snapshot?: string[];
  baseline_value?: number | null;
  candidate_value?: number | null;
  improvement_value?: number | null;
  recorded_at: string;
  judged_at?: string | null;
}

declare interface ExperimentRecord {
  id: string;
  proposal_id: string;
  commit_id: string;
  approval_id: string;
  target_agent_id: string;
  skill: string;
  hypothesis: string;
  prompt_version_from: string;
  prompt_version_to: string;
  mutation_type: string;
  acceptance_gates: string[];
  window_start: string;
  window_end: string;
  acceptance_metric: string;
  baseline_value: number;
  candidate_value: number;
  baseline_monetary_ntd?: number;
  candidate_monetary_ntd?: number;
  status: string;
  revert_reason: string;
}

declare interface FactorAttribution {
  momentum: string;
  value: string;
  quality: string;
  agent: string;
  total: string;
}

declare interface FactorDetail {
  avg_score: number;
  avg_return: number;
  contribution: number;
}

declare interface FactorExposureInline {
  momentum: number;
  value: number;
  quality: number;
  agent: number;
  total: number;
}

declare interface FactorScoreBreakdown {
  momentum: string;
  value: string;
  quality: string;
  agent: string;
  institutional_sentiment: string;
  liquidity: string;
  narrative?: string;
  industry_cycle?: string;
  total: string;
}

declare interface FactorScoreItem {
  score: number;
  weight?: number;
  formula: string;
  raw_inputs: Record<string, number>;
  is_fallback: boolean;
}

declare interface FactorScores {
  momentum: number;
  value: number;
  quality: number;
  agent: number;
  institutional_sentiment: number;
  liquidity: number;
  narrative?: number;
  industry_cycle?: number;
  total: number;
  breakdown?: string | null;
}

declare interface ForecastVsRealityItem {
  experiment_id: string;
  proposal_id: string;
  commit_id: string;
  approval_id: string;
  target_agent_id: string;
  skill: string;
  mutation_type: string;
  status: string;
  baseline_value: number;
  candidate_value: number;
  recorded_at: string;
}

declare interface ForecastVsRealityResponse {
  items: string[];
  symbol_predictions: string[];
  broker_runtime: BrokerRuntimeAudit;
}

declare interface GraphEdge {
  source: string;
  target: string;
  correlation: number;
  strength: string;
}

declare interface GraphNode {
  id: string;
  systemic_importance: number;
  upstream_count: number;
  downstream_count: number;
}

declare interface GuardOutcome {
  guard_id: string;
  guard_skill: string;
  passed: boolean;
  reason: string;
  input_count: number;
  output_count: number;
  severity: string;
}

declare interface HeatmapEntry {
  sector: string;
  confidence: string;
  reasons: string[];
}

declare interface HumanIntervention {
  id: string;
  type: string;
  target_agent_id?: string;
  target_model_id?: string;
  target_sector?: string;
  target_symbol?: string;
  value?: number;
  reason: string;
  operator: string;
  session_id?: string;
  recorded_at: string;
  expires_at?: string;
  ttl_hours?: number;
}

declare interface IndustryContextItem {
  industry_id: string;
  business_cycle: string;
  cycle_confidence: number;
  seasonal_multiplier: number;
  systemic_importance: number;
}

declare interface IndustryCycleFactorScore {
  score: number;
  phase?: string;
  phase_score?: number;
  confidence?: number;
  industry_id?: string;
}

declare interface IndustryDetail {
  id: string;
  name: string;
  name_en: string;
  description: string;
  level: number;
  weight: number;
  weight_derivation: string;
  representative_stocks: string[];
  cycle_position: string | null;
  linkage_info: string | null;
  risk_info: string | null;
  seasonal_patterns: string[];
  recommendation: string | null;
  regime_context: string;
}

declare interface IndustryOverview {
  id: string;
  name: string;
  base_weight: number;
  adjusted_weight: number;
  cycle_phase: string;
  inventory_cycle: string;
  capex_cycle: string;
  cycle_confidence: number;
  is_favorable: boolean;
  seasonal_patterns: string[];
  linkage_score: string | null;
  cycle_multiplier: number;
  seasonal_multiplier: number;
  linkage_multiplier: number;
  adjustment_log: string[];
}

declare interface IndustryRecommendation {
  action: string;
  conviction: string;
  target_weight: number;
  current_weight: number;
  delta: number;
  rationale: string;
  time_horizon: string;
  risk_adjusted: boolean;
}

declare interface IntegrityCheck {
  name: string;
  status: string;
  message: string;
}

declare interface LinkageInfo {
  industry: string;
  upstream: string[];
  downstream: string[];
  correlations: Record<string, string>[];
  linkage_score: string | null;
}

declare interface LiveStatusResponse {
  circuit_breaker: string;
  portfolio: string;
  timestamp: string;
}

declare interface MacroRadarResponse {
  session_id: string;
  regime: string;
  guard_outcomes: GuardOutcome[];
  broker_runtime: BrokerRuntimeAudit;
  recorded_at: string;
}

declare interface MetricTrendPoint {
  id: string;
  execution_id: string;
  experiment_id?: string;
  series_key: string;
  metric_name: string;
  metric_scope: string;
  metric_value: number;
  baseline_value?: number | null;
  delta_value?: number | null;
  sampled_at: string;
  tags?: string[];
}

declare interface MetricsSnapshot {
  screening_total: number;
  screening_passed: number;
  screening_rate: number;
  alerts_triggered: number;
  alerts_acknowledged: number;
  alerts_by_type: Record<string, number>;
  timestamp: string;
}

declare interface MinFilter {
  min?: number | null;
}

declare interface MonthlyReturn {
  year: number;
  month: number;
  return: number;
  label: string;
}

declare interface MutationBrief {
  contract_version?: number;
  proposal_id?: string;
  window_id: string;
  target_agent_id: string;
  target_skill: string;
  target_layer: string;
  prompt_file: string;
  mutation_type: string;
  failure_pattern: string;
  hypothesis: string;
  acceptance_metric: string;
  acceptance_gates: string[];
  forbidden_actions: string[];
  required_skills: string[];
  observed_window_count: number;
  maturity_level: string;
  iteration_guidance: string[];
  recommended_window: string;
  generated_at: string;
}

declare interface NarrativeContextItem {
  active_themes: string[];
  primary_theme?: string;
  primary_hit_rate?: number;
  direction_hint?: string;
}

declare interface NarrativeFactorScore {
  score: number;
  theme?: string;
  hit_rate?: number;
  confidence?: number;
  event_ids?: string[];
}

declare interface OOSResult {
  passed: boolean;
  baseline_score: number;
  candidate_score: number;
  improvement: number;
  observations: number;
  oos_window_start: string;
  oos_window_end: string;
  used_fallback: boolean;
  validation_at: string;
  reason: string;
}

declare interface ParameterSnapshot {
  factor_weights?: Record<string, number>;
  narrative_hit_rates?: Record<string, number>;
  industry_phase_scores?: Record<string, number>;
  config_version?: string;
  captured_at: string;
}

declare interface PerformanceReport {
  period: string;
  start_date: string;
  end_date: string;
  total_return: number;
  annualized_return: number;
  sharpe_ratio: number;
  sortino_ratio: number;
  calmar_ratio: number;
  max_drawdown: number;
  starting_value: number;
  ending_value: number;
  after_tax_value: number;
  total_tax_paid: number;
  win_rate: number;
  total_trades: number;
  avg_win: number;
  avg_loss: number;
  top_agents: string[];
  regime_breakdown: string;
  monthly_returns: string[];
  generated_at: string;
}

declare interface PipelineItem {
  symbol: string;
  agent_id: string;
  skill: string;
  layer: string;
  side: string;
  conviction: number;
  target_price: number;
  stop_loss_price: number;
  forward_return: number;
  hit: boolean;
  reason: string;
  price: number;
  passed_guards: boolean;
  guard_reason: string;
  tags: string[];
  recorded_at: string;
  factor_scores: FactorScores;
  conviction_breakdown?: ConvictionBreakdown | null;
  narrative_event_ids?: string[];
  narrative_context?: string | null;
  industry_context?: string | null;
  metrics?: string | null;
}

declare interface PipelineItemMetrics {
  price_to_earnings?: number | null;
  price_to_book?: number | null;
  dividend_yield?: number | null;
  backtest_return?: number | null;
}

declare interface PipelineSourceStatus {
  source_id: string;
  producer: string;
  consumer: string;
  last_produced: string;
  last_consumed: string;
  status: string;
  lag_human: string;
  file_path: string;
}

declare interface PnLAttributionResponse {
  snapshot_time: string;
  session_id: string;
  starting_value: number;
  current_value: number;
  cumulative_pnl: number;
  cumulative_return_pct: number;
  agent_attribution: string[];
  sector_attribution: string[];
  factor_attribution: string;
  symbol_attribution: string[];
}

declare interface PortfolioStateResponse {
  snapshot_time: string;
  cash: number;
  starting_cash?: number;
  portfolio_value: number;
  realized_pnl?: number;
  cumulative_pnl: number;
  cumulative_pnl_pct: number;
  current_drawdown: number;
  unrealized_pnl_total?: number;
  concentration_ratio?: number;
  trade_count?: number;
  positions_count: number;
  positions: string[];
  equity_curve: string[];
  cross_foot_pnl: string;
}

declare interface PortfolioSummary {
  cash: number;
  available_cash: number;
  total_exposure: number;
  day_pnl: number;
  unrealized_pnl: number;
  positions_count: number;
}

declare interface Position {
  symbol: string;
  quantity: number;
  average_cost: number;
  current_price: number;
  market_value: number;
  unrealized_pnl: number;
}

declare interface PositionConcentration {
  symbol: string;
  market_value: number;
  weight: number;
}

declare interface PositionDTO {
  symbol: string;
  quantity: number;
  average_cost: number;
  current_price: number;
  market_value: number;
  unrealized_pnl: number;
  pnl_pct: number;
  sector?: string;
}

declare interface PremarketData {
  us_market: Record<string, string>;
  foreign_flow: Record<string, string>;
  fx: Record<string, string>;
  bdi: Record<string, string>;
  vix?: Record<string, string>;
  stress_index?: Record<string, string>;
}

declare interface PromptControl {
  volume_floor?: number;
  volume_downgrade?: number;
  close_strength_boost?: number;
  hard_reject_volume?: number;
  price_condition?: string;
  conviction_floor?: number;
  volume_boost?: number;
  require_trend?: boolean;
  neutral_penalty_reduction?: number;
}

declare interface PromptExperimentResult {
  experiment: string;
  brief: string;
  candidate_prompt: string;
  evaluation_mode: string;
  policy_checks: string[];
  notes: string[];
  judge_checks: string[];
  baseline_observations: number;
  candidate_observations: number;
  used_fallback_window: boolean;
  recorded_at: string;
  data_metadata?: string | null;
  oos_result?: string | null;
  baseline_returns?: number[];
  candidate_returns?: number[];
  parameter_snapshot_id?: string;
  baseline_fallback_count?: number;
  candidate_fallback_count?: number;
  baseline_factor_count?: number;
  candidate_factor_count?: number;
  baseline_monetary_ntd?: number;
  candidate_monetary_ntd?: number;
}

declare interface Quote {
  symbol: string;
  last: number;
  open: number;
  high: number;
  low: number;
  volume: number;
  market: string;
  as_of: string;
  is_tradable: boolean;
  source: string;
}

declare interface RangeFilter {
  min?: number | null;
  max?: number | null;
}

declare interface ReasoningTraceItem {
  session_id: string;
  timestamp: string;
  phase: string;
  step: number;
  component: string;
  action: string;
  reasoning: string;
  data?: string;
  confidence: number;
  is_fallback: boolean;
  explanation: string;
  raw_data?: string;
}

declare interface ReasoningTraceResponse {
  session_id: string;
  traces: string[];
}

declare interface RecEntry {
  symbol: string;
  name: string;
  action: string;
  shares?: number;
  confidence: number;
  reasons: string[];
}

declare interface Recommendation {
  reasoning_chain?: string[];
  supporting_events?: string[];
  factor_scores: FactorScores;
  conviction_breakdown?: ConvictionBreakdown | null;
}

declare interface RecommendationOutcome {
  agent_id: string;
  skill: string;
  layer: string;
  symbol: string;
  side: string;
  conviction: number;
  target_price: number;
  stop_loss_price: number;
  window: string;
  forward_return: number;
  benchmark_delta: number;
  hit: boolean;
  hit_rate: number;
  reason: string;
  price: number;
  passed_guards: boolean;
  guard_reason: string;
  recorded_at: string;
  factor_scores: FactorScores;
  conviction_breakdown?: ConvictionBreakdown | null;
  supporting_events?: string[];
  parameter_snapshot?: ParameterSnapshot | null;
  is_synthetic: boolean;
}

declare interface RecommendationPipelineResponse {
  session_id: string;
  regime: string;
  items: string[];
  guard_outcomes: GuardOutcome[];
  screened_items: ScreeningReject[];
  recorded_at: string;
  is_fallback_session: boolean;
  fallback_message: string;
}

declare interface RegimeBreakdown {
  regimes: Record<string, string>;
}

declare interface RegimeHistoryData {
  sessions: string[];
  transitions: string[];
  current_regime: string;
}

declare interface RegimePerformance {
  regime: string;
  session_count: number;
  total_return: number;
  win_rate: number;
  avg_return: number;
}

declare interface RegimeSessionEntry {
  session_id: string;
  regime: string;
  recorded_at: string;
}

declare interface RegimeTransition {
  from_regime: string;
  to_regime: string;
  timestamp: string;
}

declare interface ReplayDataMetadata {
  source_path: string;
  date_range_start: string;
  date_range_end: string;
  days_delayed: number;
  covers_window: boolean;
  last_modified: string;
  record_count: number;
}

declare interface ReportEntry {
  filename: string;
  path: string;
  updated_at: string;
}

declare interface ReportSection {
  title: string;
  content: string;
  priority: number;
}

declare interface RetailSentimentResponse {
  sentiment_score: number;
  margin_change_pct: number;
  margin_balance: number;
  short_balance: number;
  short_change_pct: number;
  day_trading_ratio: number;
  margin_percentile: number;
  extreme_reading: string;
  score: number;
  change_pct: number;
  interpretation: string;
}

declare interface RetailSentimentSnapshot {
  margin_balance: number;
  margin_change_pct: number;
  day_trading_ratio: number;
  margin_percentile: number;
  timestamp: string;
}

declare interface RiskExposureResponse {
  snapshot_time: string;
  var_95: number;
  var_99: number;
  cvar_95: number;
  max_drawdown_pct: number;
  portfolio_value: number;
  cash_ratio: number;
  position_count: number;
  sector_exposure: string[];
  factor_exposure: string;
  concentration: string[];
  data_points: number;
  insufficient_data: boolean;
}

declare interface RiskInfo {
  symbol: string;
  industry: string;
  risk_count: number;
  risks: Record<string, string>[];
  highest_risk: Record<string, string>;
}

declare interface RiskSnapshot {
  var_95: number;
  var_99: number;
  cvar_95: number;
  max_drawdown_pct: number;
}

declare interface RuleSummary {
  id: string;
  pattern: string;
  hit_rate: number;
  affected_sectors: string[];
  direction: string;
  status: string;
}

declare interface Scorecard {
  agent_id: string;
  skill: string;
  layer: string;
  observations: number;
  windows: number;
  hit_rate: number;
  average_return: number;
  sharpe: number;
  max_drawdown: number;
  concentration_warnings: number;
  last_updated_at: string;
}

declare interface ScreeningCriteria {
  pe?: string | null;
  pb?: string | null;
  dividend_yield?: string | null;
  momentum_20d?: string | null;
  volatility_20d?: string | null;
  volume_intraday?: string | null;
  min_total_factor_score?: number | null;
  required_factors?: string[];
}

declare interface ScreeningReject {
  session_id: string;
  symbol: string;
  agent_id: string;
  skill: string;
  criterion: string;
  criterion_label: string;
  threshold: string;
  actual_value: string;
  factor_scores: FactorScores;
  recorded_at: string;
}

declare interface SeasonalExpectation {
  theme: string;
  historical_avg_return: number;
  current_return: number;
  expectation_gap: number;
  already_priced_in: boolean;
}

declare interface SeasonalPattern {
  id: string;
  name: string;
  name_en?: string;
  description: string;
  start_month: number;
  start_day: number;
  end_month: number;
  end_day: number;
  historical_accuracy: number;
  typical_return: number;
  adjustment_factor: number;
  favored_industries?: string[];
  avoided_industries?: string[];
  affected_industries?: string[];
  impact?: string;
}

declare interface SectorAttribution {
  sector: string;
  sector_label: string;
  total_return: number;
  count: number;
  avg_return: number;
}

declare interface SectorExposure {
  sector: string;
  sector_label: string;
  weight: number;
  est_value: number;
}

declare interface SessionSummary {
  session_id: string;
  regime: string;
  order_count: number;
  position_count: number;
  ending_cash: number;
  portfolio_value: number;
  outcome_count: number;
  broker_runtime: string;
  next_experiment_agent_id: string;
  proposal_id: string;
  commit_id: string;
  approval_id: string;
  guard_outcomes: string[];
  recorded_at: string;
  tax_snapshots?: string[];
  after_tax_pnl: number;
  total_tax_paid: number;
  parameters_version?: string;
}

declare interface ShockImpact {
  industry: string;
  impact: number;
}

declare interface SimulationConstraints {
  starting_cash: number;
  max_position_weight: number;
  max_open_positions: number;
  min_tradable_volume: number;
  min_recommendation_conviction: number;
  require_cro_pass: boolean;
  transaction_cost_bps: number;
  slippage_bps: number;
  reserve_cash_fraction: number;
  stop_loss_pct: number;
  take_profit_pct: number;
}

declare interface SimulationReport {
  total_return: number;
  sharpe_ratio: number;
  max_drawdown: number;
  equity_curve: number[];
  agent_hit_rates: Record<string, number>;
  trade_count: number;
  start_date: string;
  end_date: string;
  fallback_events?: string[];
}

declare interface SimulationResult {
  risk_snapshot?: string | null;
  tax_snapshots?: string[];
  before_tax_pnl: number;
  after_tax_pnl: number;
  total_tax_paid: number;
  fallback_events?: string[];
}

declare interface SimulationState {
  cash: number;
  positions: string[];
  realized_pnl: number;
  starting_cash: number;
  equity_curve: number[];
  daily_returns: number[];
  previous_values: Record<string, number>;
  max_equity: number;
  current_drawdown: number;
}

declare interface SymbolAttribution {
  symbol: string;
  total_return: number;
  count: number;
  avg_return: number;
  side: string;
}

declare interface SymbolPredictionItem {
  agent_id: string;
  symbol: string;
  side: string;
  conviction: number;
  target_price: number;
  forward_return: number;
  hit: boolean;
  passed_guards: boolean;
  recorded_at: string;
  session_id: string;
}

declare interface SystemHealthResponse {
  baseline_version: string;
  replay_data_latest_date: string;
  replay_data_path_ok: boolean;
  last_window_id: string;
  last_window_generated_at: string;
  warnings: string[];
  regime: string;
  data_channels?: string[];
  cycle_stale: boolean;
}

declare interface TaskExecution {
  id: string;
  task_type: string;
  command_name: string;
  command_args?: string[];
  request_payload?: string[];
  status: string;
  actor: string;
  actor_source: string;
  idempotency_key?: string;
  retry_of?: string;
  parent_execution_id?: string;
  experiment_id?: string;
  result_path?: string;
  baseline_version_before?: number | null;
  baseline_version_after?: number | null;
  requires_confirmation: boolean;
  confirmed_at?: string | null;
  cancel_requested_at?: string | null;
  submitted_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  exit_code?: number | null;
  error_message?: string;
  summary?: string[];
  created_at: string;
  updated_at: string;
}

declare interface TaskExecutionEvent {
  execution_id: string;
  sequence: number;
  event_type: string;
  stream: string;
  level?: string;
  message: string;
  payload?: string[];
  created_at: string;
}

declare interface TaxConfig {
  dividend_tax_rate: number;
  transaction_tax_rate: number;
  include_nhi: boolean;
}

declare interface TaxSnapshot {
  symbol: string;
  dividend_tax_rate: number;
  transaction_tax_rate: number;
  dividend_tax: number;
  transaction_tax: number;
  total_tax: number;
  after_tax_pnl: number;
}

declare interface TradeRecord {
  trade_id: string;
  session_id: string;
  symbol: string;
  side: string;
  quantity: number;
  price: number;
  amount: number;
  reason?: string;
  timestamp: string;
}

declare interface TrendPoint {
  timestamp: string;
  value: number;
}

declare interface UniverseOverlapResponse {
  agents: string[];
  matrix: Record<string, Record<string, number>>;
  warnings: string[];
}

declare interface WeightDerivation {
  base_weight: number;
  derivation_factors: string[];
  interpretation: string;
  risk_factors: string[];
  opportunities: string[];
}

declare interface WeightFactor {
  factor: string;
  contribution: number;
  source: string;
  evidence: string;
}

declare interface rawOutcome {
  agent_id: string;
  symbol: string;
  side: string;
  conviction: number;
  target_price: number;
  forward_return: number;
  hit: boolean;
  passed_guards: boolean;
  recorded_at: string;
  session_id: string;
}

declare interface submitTaskRequest {
  task_type: string;
  payload?: Record<string, string>;
  confirmed?: boolean;
  idempotency_key?: string;
}

declare interface submitTaskResponse {
  id: string;
  status: string;
}

