// Auto-generated by cmd/gentags. DO NOT EDIT.
// Run: go generate ./...  or  go run ./cmd/gentags
// Source: internal/domain/*.go json tags

declare interface AgentSpec {
  darwinian_weight?: number;
  screening_criteria?: string;
}

declare interface AlertChannelConfig {
  telegram_bot_token?: string;
  telegram_chat_id?: string;
  email_smtp_host?: string;
  email_smtp_port?: number;
  email_from?: string;
  email_to?: string[];
  email_password?: string;
  webhook_url?: string;
  webhook_headers?: Record<string, string>;
}

declare interface AlertRecord {
  id: string;
  timestamp: string;
  rule: string;
  severity: string;
  message: string;
  value: number;
  threshold: number;
  acknowledged: boolean;
  acknowledged_at?: string | null;
  acknowledged_by?: string;
}

declare interface BacktestWindowSummary {
  window_id: string;
  start_date: string;
  end_date: string;
  session_count: number;
  outcome_count: number;
  worst_agent_id: string;
  worst_agent_skill: string;
  worst_agent_layer: string;
  worst_agent_window_count: number;
  worst_agent_sharpe_like: number;
  generated_at: string;
}

declare interface BaselineHistoryRecord {
  id: string;
  execution_id?: string;
  experiment_id?: string;
  version_before: number;
  version_after: number;
  promoted_by: string;
  promoted_at: string;
  baseline_path: string;
  diff_summary?: string[];
  diff_patch?: string;
  metadata?: string[];
}

declare interface BrokerRuntimeAudit {
  mode: string;
  adapter: string;
  signer: string;
  signer_version: string;
  key_id: string;
  max_retries: number;
  http_timeout_sec: number;
  http_attempts: number;
  retry_status_codes: number[];
  max_clock_skew_sec: number;
  nonce_ttl_sec: number;
  nonce_store: string;
  nonce_store_path: string;
  nonce_redis_prefix: string;
}

declare interface CapitalPhaseConfig {
  current_phase: string;
  phase_start_date: string;
  min_days_per_phase: number;
  max_drawdown_limit: number;
  sharpe_threshold: number;
  capital_limits: Record<string, number>;
  max_consecutive_losses: number;
}

declare interface CapitalSnapshot {
  phase: string;
  phase_start_date: string;
  days_in_phase: number;
  total_capital: number;
  deployed_capital: number;
  reserve_cash: number;
  rolling_sharpe: number;
  max_drawdown: number;
  consecutive_losses: number;
  can_advance: boolean;
  advance_reason?: string;
}

declare interface ConvictionBreakdown {
  base: number;
  floor: number;
  final: number;
  steps: string[];
}

declare interface ConvictionStep {
  rule: string;
  delta: number;
  reason: string;
}

declare interface DailyBar {
  date: string;
  symbol: string;
  name: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  source: string;
}

declare interface DailySummaryReport {
  date: string;
  sections: string[];
  top_picks: string[];
  risk_level: string;
  narrative_count: number;
}

declare interface DayResult {
  date: string;
  regime: string;
  orders: string[];
  positions: string[];
  cash: number;
  portfolio_value: number;
  daily_pnl: number;
}

declare interface ExecutionPolicy {
  conviction_floor: number;
  require_cro_pass: boolean;
  momentum_crash_protection: boolean;
  enable_conviction_normalization: boolean;
}

declare interface ExperimentLineageRecord {
  experiment_id: string;
  execution_id: string;
  parent_experiment_id?: string;
  root_experiment_id: string;
  lineage_depth: number;
  target_agent_id: string;
  target_skill: string;
  mutation_type: string;
  brief_path?: string;
  candidate_path?: string;
  result_path?: string;
  status: string;
  git_commit_id?: string;
  params_snapshot?: string[];
  result_snapshot?: string[];
  baseline_value?: number | null;
  candidate_value?: number | null;
  improvement_value?: number | null;
  recorded_at: string;
  judged_at?: string | null;
}

declare interface ExperimentRecord {
  id: string;
  proposal_id: string;
  commit_id: string;
  approval_id: string;
  target_agent_id: string;
  skill: string;
  hypothesis: string;
  prompt_version_from: string;
  prompt_version_to: string;
  mutation_type: string;
  acceptance_gates: string[];
  window_start: string;
  window_end: string;
  acceptance_metric: string;
  baseline_value: number;
  candidate_value: number;
  status: string;
  revert_reason: string;
}

declare interface FactorScoreBreakdown {
  momentum: string;
  value: string;
  quality: string;
  agent: string;
  institutional_sentiment: string;
  liquidity: string;
  total: string;
}

declare interface FactorScoreItem {
  score: number;
  weight?: number;
  formula: string;
  raw_inputs: Record<string, number>;
  is_fallback: boolean;
}

declare interface FactorScores {
  momentum: number;
  value: number;
  quality: number;
  agent: number;
  institutional_sentiment: number;
  liquidity: number;
  total: number;
  breakdown?: string | null;
}

declare interface GuardOutcome {
  guard_id: string;
  guard_skill: string;
  severity: string;
  passed: boolean;
  reason: string;
  input_count: number;
  output_count: number;
}

declare interface HumanIntervention {
  id: string;
  type: string;
  target_agent_id?: string;
  target_model_id?: string;
  target_sector?: string;
  target_symbol?: string;
  value?: number;
  reason: string;
  operator: string;
  session_id?: string;
  recorded_at: string;
}

declare interface MetricTrendPoint {
  id: string;
  execution_id: string;
  experiment_id?: string;
  series_key: string;
  metric_name: string;
  metric_scope: string;
  metric_value: number;
  baseline_value?: number | null;
  delta_value?: number | null;
  sampled_at: string;
  tags?: string[];
}

declare interface MinFilter {
  min?: number | null;
}

declare interface MutationBrief {
  contract_version?: number;
  proposal_id?: string;
  window_id: string;
  target_agent_id: string;
  target_skill: string;
  target_layer: string;
  prompt_file: string;
  mutation_type: string;
  failure_pattern: string;
  hypothesis: string;
  acceptance_metric: string;
  acceptance_gates: string[];
  forbidden_actions: string[];
  required_skills: string[];
  observed_window_count: number;
  maturity_level: string;
  iteration_guidance: string[];
  recommended_window: string;
  generated_at: string;
}

declare interface OOSResult {
  passed: boolean;
  baseline_score: number;
  candidate_score: number;
  improvement: number;
  observations: number;
  oos_window_start: string;
  oos_window_end: string;
  used_fallback: boolean;
  validation_at: string;
  reason: string;
}

declare interface Position {
  symbol: string;
  quantity: number;
  average_cost: number;
  current_price: number;
  market_value: number;
  unrealized_pnl: number;
}

declare interface PromptControl {
  volume_floor?: number;
  volume_downgrade?: number;
  close_strength_boost?: number;
  hard_reject_volume?: number;
  price_condition?: string;
  conviction_floor?: number;
  volume_boost?: number;
  require_trend?: boolean;
  neutral_penalty_reduction?: number;
}

declare interface PromptExperimentResult {
  experiment: string;
  brief: string;
  candidate_prompt: string;
  evaluation_mode: string;
  policy_checks: string[];
  notes: string[];
  judge_checks: string[];
  baseline_observations: number;
  candidate_observations: number;
  used_fallback_window: boolean;
  recorded_at: string;
  data_metadata?: string | null;
  oos_result?: string | null;
  baseline_returns?: number[];
  candidate_returns?: number[];
  parameter_snapshot_id?: string;
  baseline_fallback_count?: number;
  candidate_fallback_count?: number;
  baseline_factor_count?: number;
  candidate_factor_count?: number;
}

declare interface Quote {
  symbol: string;
  last: number;
  open: number;
  high: number;
  low: number;
  volume: number;
  market: string;
  as_of: string;
  is_tradable: boolean;
  source: string;
}

declare interface RangeFilter {
  min?: number | null;
  max?: number | null;
}

declare interface Recommendation {
  reasoning_chain?: string[];
  supporting_events?: string[];
  factor_scores?: string;
  conviction_breakdown?: string | null;
}

declare interface RecommendationOutcome {
  agent_id: string;
  skill: string;
  layer: string;
  symbol: string;
  side: string;
  conviction: number;
  target_price: number;
  stop_loss_price: number;
  window: string;
  forward_return: number;
  benchmark_delta: number;
  hit: boolean;
  reason: string;
  price: number;
  passed_guards: boolean;
  guard_reason: string;
  recorded_at: string;
  factor_scores?: string;
  conviction_breakdown?: string | null;
}

declare interface ReplayDataMetadata {
  source_path: string;
  date_range_start: string;
  date_range_end: string;
  days_delayed: number;
  covers_window: boolean;
  last_modified: string;
  record_count: number;
}

declare interface ReportSection {
  title: string;
  content: string;
  priority: number;
}

declare interface RetailSentimentSnapshot {
  margin_balance: number;
  margin_change_pct: number;
  day_trading_ratio: number;
  margin_percentile: number;
  timestamp: string;
}

declare interface RiskSnapshot {
  var_95: number;
  var_99: number;
  cvar_95: number;
  max_drawdown_pct: number;
}

declare interface Scorecard {
  agent_id: string;
  skill: string;
  layer: string;
  observations: number;
  windows: number;
  hit_rate: number;
  average_return: number;
  sharpe: number;
  max_drawdown: number;
  concentration_warnings: number;
  last_updated_at: string;
}

declare interface ScreeningCriteria {
  pe?: string | null;
  pb?: string | null;
  dividend_yield?: string | null;
  momentum_20d?: string | null;
  volatility_20d?: string | null;
  volume_intraday?: string | null;
  min_total_factor_score?: number | null;
  required_factors?: string[];
}

declare interface ScreeningReject {
  session_id: string;
  symbol: string;
  agent_id: string;
  skill: string;
  criterion: string;
  criterion_label: string;
  threshold: string;
  actual_value: string;
  factor_scores?: string;
  recorded_at: string;
}

declare interface SessionSummary {
  session_id: string;
  regime: string;
  order_count: number;
  position_count: number;
  ending_cash: number;
  portfolio_value: number;
  outcome_count: number;
  broker_runtime: string;
  next_experiment_agent_id: string;
  proposal_id: string;
  commit_id: string;
  approval_id: string;
  guard_outcomes: string[];
  recorded_at: string;
  tax_snapshots?: string[];
  after_tax_pnl: number;
  total_tax_paid: number;
}

declare interface SimulationConstraints {
  starting_cash: number;
  max_position_weight: number;
  max_open_positions: number;
  min_tradable_volume: number;
  min_recommendation_conviction: number;
  require_cro_pass: boolean;
  transaction_cost_bps: number;
  slippage_bps: number;
  reserve_cash_fraction: number;
  stop_loss_pct: number;
  take_profit_pct: number;
}

declare interface SimulationReport {
  total_return: number;
  sharpe_ratio: number;
  max_drawdown: number;
  equity_curve: number[];
  agent_hit_rates: Record<string, number>;
  trade_count: number;
  start_date: string;
  end_date: string;
}

declare interface SimulationResult {
  risk_snapshot?: string | null;
  tax_snapshots?: string[];
  before_tax_pnl: number;
  after_tax_pnl: number;
  total_tax_paid: number;
}

declare interface SimulationState {
  cash: number;
  positions: string[];
  cumulative_pnl: number;
  equity_curve: number[];
  daily_returns: number[];
  previous_values: Record<string, number>;
  max_equity: number;
  current_drawdown: number;
}

declare interface TaskExecution {
  id: string;
  task_type: string;
  command_name: string;
  command_args?: string[];
  request_payload?: string[];
  status: string;
  actor: string;
  actor_source: string;
  idempotency_key?: string;
  retry_of?: string;
  parent_execution_id?: string;
  experiment_id?: string;
  result_path?: string;
  baseline_version_before?: number | null;
  baseline_version_after?: number | null;
  requires_confirmation: boolean;
  confirmed_at?: string | null;
  cancel_requested_at?: string | null;
  submitted_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  exit_code?: number | null;
  error_message?: string;
  summary?: string[];
  created_at: string;
  updated_at: string;
}

declare interface TaskExecutionEvent {
  execution_id: string;
  sequence: number;
  event_type: string;
  stream: string;
  level?: string;
  message: string;
  payload?: string[];
  created_at: string;
}

declare interface TaxConfig {
  dividend_tax_rate: number;
  transaction_tax_rate: number;
  include_nhi: boolean;
}

declare interface TaxSnapshot {
  symbol: string;
  dividend_tax_rate: number;
  transaction_tax_rate: number;
  dividend_tax: number;
  transaction_tax: number;
  total_tax: number;
  after_tax_pnl: number;
}

