#!/usr/bin/env bash
# check_field_contract.sh — validate JS field accesses against Go JSON tags
#
# Reads valid_fields.json (generated by cmd/gentags) and scans JS files
# for dot-accessed snake_case fields. Any field not in the allowlist is
# flagged as a potential frontend-backend contract mismatch.
#
# Usage: bash scripts/ci/check_field_contract.sh [--strict]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Use shared_web as canonical source (gentags writes identical copies to all 3 active dirs)
VALID_FIELDS="$REPO_ROOT/shared_web/static/js/shared/valid_fields.json"
# Scan JS across all active frontend directories.
JS_DIRS=("$REPO_ROOT/admin_web/static/js" "$REPO_ROOT/client_web/static/js" "$REPO_ROOT/shared_web/static/js")

if [ ! -f "$VALID_FIELDS" ]; then
  echo "ERROR: valid_fields.json not found. Run 'go generate .' first."
  exit 1
fi

# Wait for valid_fields.json to be fully written by go generate (race robustness).
# go generate may leave the file empty/truncated for a brief moment.
MAX_WAIT=10
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
  if [ -s "$VALID_FIELDS" ] && jq -e '.' "$VALID_FIELDS" >/dev/null 2>&1; then
    break
  fi
  sleep 0.2
  WAITED=$((WAITED + 1))
done
if [ $WAITED -eq $MAX_WAIT ]; then
  echo "ERROR: valid_fields.json is missing, empty, or truncated after ${MAX_WAIT} retries."
  ls -la "$VALID_FIELDS" || true
  exit 1
fi

# Build allowlist from valid_fields.json (extract JSON array to grep-friendly list)
ALLOWLIST=$(mktemp)
jq -r '.[]' "$VALID_FIELDS" > "$ALLOWLIST"
ALLOW_COUNT=$(wc -l < "$ALLOWLIST" | tr -d ' ')
echo "✓ Loaded $ALLOW_COUNT valid field names from valid_fields.json"

# Collect all dot-accessed snake_case fields from JS files.
# Pattern: matches `.field_name` where field_name contains at least one underscore
# and is followed by a non-word boundary (comma, space, semicolon, newline, etc.)
VIOLATIONS=0
FOUND_FIELDS=$(mktemp)

# Global violation accumulator (aggregates across all JS dirs)
VIOLATIONS=0
FOUND_FIELDS=$(mktemp)

for JS_DIR in "${JS_DIRS[@]}"; do
  [ ! -d "$JS_DIR" ] && continue
  while IFS= read -r file; do
    perl -ne 'while (/\.([a-z][a-z0-9]*(?:_[a-z0-9]+)+)(?=[^a-zA-Z0-9_])/g) { print "$1\n" }' "$file" 2>/dev/null | \
    while IFS= read -r field; do
      case "$field" in
        replace_state|page_load|auto_refresh|load_page|switch_page|render_overview|\
        render_pipeline|render_macro|render_live|render_tool|render_inbox|\
        render_backtest|render_evolution|render_parameters|render_synergy|\
        load_all|load_modules|load_data|get_json|safe_get|format_date|escape_html|\
        agent_name|stock_name|event_name|stress_label|sector_name|regime_label|\
        fmt_ntd|num_results|pass_guards|target_price|stop_loss|forward_return|\
        show_all|session_id|agent_id|channel_id|recorded_at|updated_at|created_at|\
        class_name|on_click|data_page|data_theme|key_id|\
        active_patterns|adjustment_breakdown|all_patterns|\
        affected_sectors|avoided_sectors|favored_sectors|banned_sectors|\
        annualized_return|baseline_prompt|\
        calibration_evidence|capital_flow|changed_at|\
        concentration_score|confidence_source|consecutive_failures|\
        data_source|dealer_net|domestic_fund_net|event_id|\
        fetch_at|foreign_investor_net|geo_error|geo_ok|\
        historical_hit_rate|impact_count|impact_estimate|last_run|\
        macro_error|macro_ok|market_close_time|market_hours_only|\
        market_open_time|max_age_days|monthly_returns|narrative_themes|\
        new_value|old_value|oldest_kept|orders_evaluated|\
        paused_agents|prism_completed_results|recent_error|regime_since|\
        retail_margin_balance|retail_short_balance|session_span|\
        sharpe_like|shock_propagation_speed|signal_count|\
        source_references|swarm_running|template_id|time_window|\
        top_agents|total_assets|total_deleted|total_kept|\
        trigger_theme|usd_twd|\
        sox_pct|net_buy_twd|deviation_pct|change_pct|\
        exit_alerts|logic_rules|sector_heatmap|\
        confidence_breakdown) continue ;;
        backtest_completed|calibration_completed) continue ;;
        auto_discovered_count|auto_discovered_rules|\
        avg_improvement|convergence_rate|success_rate|stability_score|\
        confidence_score|oil_pct|vix_level|\
        core_indicators|last_24h|next_run|\
        empty_state|gate_mode|\
        action_type|action_description|confidence_commentary|\
        agent_skill|signals_count|\
        foreign_capital_signal|foreign_investor_net_billions|\
        taiwan_ex_change_pct|taiwan_ex_direction|\
        total_pnl|total_value|\
        sample_days|strategy_id|strategy_name|\
        condition_id|rolling_window|wilson_lower|wilson_upper|\
        avg_forward_return|data_start|data_end) continue ;;
      esac

      echo "$field" >> "$FOUND_FIELDS"
    done
  done < <(find "$JS_DIR" -name '*.js' -not -path '*/shared/field_*' -not -path '*/shared/valid_*')
done

# Deduplicate found fields
sort -u "$FOUND_FIELDS" -o "$FOUND_FIELDS"
FOUND_COUNT=$(wc -l < "$FOUND_FIELDS" | tr -d ' ')

# Check each found field against allowlist
UNKNOWN=$(mktemp)
while IFS= read -r field; do
  if [ -z "$field" ]; then
    continue
  fi
  if ! grep -qxF "$field" "$ALLOWLIST"; then
    echo "$field" >> "$UNKNOWN"
  fi
done < "$FOUND_FIELDS"

UNKNOWN_COUNT=$(wc -l < "$UNKNOWN" | tr -d ' ')
echo "✓ Scanned $FOUND_COUNT unique snake_case fields"
echo "⚠ Unknown fields: $UNKNOWN_COUNT"

if [ "$UNKNOWN_COUNT" -gt 0 ]; then
  echo ""
  echo "--- POTENTIAL CONTRACT MISMATCHES ---"
  echo "These fields appear in JS but NOT in any Go JSON tag:"
  echo ""
  while IFS= read -r field; do
    echo "  $field — used in:"
    for D in "${JS_DIRS[@]}"; do
      [ ! -d "$D" ] && continue
      matches=$(grep -rn "\.${field}[^a-zA-Z0-9_]" "$D" 2>/dev/null | head -3 || true)
      if [ -n "$matches" ]; then
        echo "$matches" | while IFS= read -r match; do
          echo "    $match"
        done
      fi
    done
    echo ""
  done < "$UNKNOWN"
  echo "If these are valid API fields, add them to the Go struct with a json tag."
  echo "If these are internal JS variables, add them to the skip list in this script."
fi

rm -f "$ALLOWLIST" "$FOUND_FIELDS" "$UNKNOWN"

if [ "${1:-}" = "--strict" ] && [ "$UNKNOWN_COUNT" -gt 0 ]; then
  echo "❌ FAIL: $UNKNOWN_COUNT unknown fields (strict mode)"
  exit 1
fi

if [ "$UNKNOWN_COUNT" -gt 0 ]; then
  echo "⚠️  WARNING: $UNKNOWN_COUNT fields not found in Go JSON tags (non-strict mode — review above)"
fi

echo "✓ Field contract check complete"
