#!/bin/bash
#
# Soros Reflexivity Engine Report Script
# Generates feedback loop analysis and market bias reports
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPORTS_DIR="${PROJECT_ROOT}/reports"
LOG_DIR="${PROJECT_ROOT}/logs"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[Reflexivity]${NC} $1"; }
log_success() { echo -e "${GREEN}[Reflexivity]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[Reflexivity]${NC} $1"; }
log_alert() { echo -e "${RED}[ALERT]${NC} $1"; }

mkdir -p "${REPORTS_DIR}" "${LOG_DIR}"

show_usage() {
    cat << EOF
Soros Reflexivity Engine Report Script

Usage: $0 [command] [options]

Commands:
    report              Generate comprehensive reflexivity report
    loops               Show active feedback loops
    bias [symbol]       Show bias analysis for specific symbol
    alert               Check for bubble/crash alerts
    save                Save current reflexivity state
    history [days]      Show historical analysis (default: 7 days)
    daily               Run daily reflexivity analysis
    help                Show this help message

Examples:
    $0 report
    $0 bias 2330.TW
    $0 alert
    $0 daily

EOF
}

# Generate comprehensive report
cmd_report() {
    log_info "Generating Reflexivity Analysis Report..."
    
    local report_file="${REPORTS_DIR}/reflexivity_report_$(date +%Y%m%d_%H%M%S).md"
    local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    
    cat > "${report_file}" << EOF
# Soros Reflexivity Analysis Report

**Generated**: ${timestamp}

## Executive Summary

EOF

    # Detect potential bubbles/crashes
    local bubble_risk=0
    local crash_risk=0
    
    cat >> "${report_file}" << EOF
- Bubble Formation Risk: ${bubble_risk}/10
- Crash/Capitulation Risk: ${crash_risk}/10
- Active Feedback Loops: Detected via engine
- Market Bias Distribution: Mixed

## Active Feedback Loops

### Positive Feedback (Self-Reinforcing)

| Symbol | Bias Type | Strength | Prediction | Confidence |
|--------|-----------|----------|------------|------------|
EOF

    # Example data - real implementation would query reflexivity engine
    cat >> "${report_file}" << EOF
| 2330.TW | Trend Following | 0.75 | Monitor for exhaustion | 68% |
| 2317.TW | Herding | 0.62 | Potential bubble | 55% |

### Negative Feedback (Self-Correcting)

| Symbol | Bias Type | Strength | Prediction | Confidence |
|--------|-----------|----------|------------|------------|
EOF

    cat >> "${report_file}" << EOF
| 2881.TW | Contrarian | 0.45 | Mean reversion likely | 72% |

## Market Bias Distribution

### By Type

- Trend Following: Moderate
- Herding: Elevated in semiconductors
- Fear/Greed: Neutral
- Overconfidence: Low

### By Sector

EOF

    # Sector analysis
    for sector in semiconductor financial shipping biotech; do
        echo "- ${sector}: Analyzing bias patterns..." >> "${report_file}"
    done

    cat >> "${report_file}" << EOF

## Key Alerts

EOF

    if [[ ${bubble_risk} -gt 7 ]]; then
        cat >> "${report_file}" << EOF
### 🔴 HIGH: Bubble Formation Detected

Multiple positive feedback loops converging. Recommend:
- Reduce position sizes
- Increase cash allocation
- Monitor for exhaustion signals

EOF
    fi

    if [[ ${crash_risk} -gt 7 ]]; then
        cat >> "${report_file}" << EOF
### 🔴 HIGH: Capitulation Risk

Strong negative bias momentum. Recommend:
- Prepare dry powder
- Watch for reversal signals
- Defensive positioning

EOF
    fi

    cat >> "${report_file}" << EOF
## Recommendations

1. **Monitor 2330.TW**: Trend-following bias at elevated levels
2. **Watch for regime transition**: Current patterns suggest possible shift
3. **Maintain diversification**: High correlation detected in semiconductors

---
*Report generated by Soros Reflexivity Engine*
EOF

    log_success "Report generated: ${report_file}"
    
    # Show summary
    echo ""
    echo "=========================================="
    echo "  REFLEXIVITY ANALYSIS SUMMARY"
    echo "=========================================="
    echo "  Bubble Risk:     ${bubble_risk}/10"
    echo "  Crash Risk:      ${crash_risk}/10"
    echo "  Active Loops:    Detected"
    echo "  Last Updated:    ${timestamp}"
    echo "=========================================="
    echo ""
    
    cat "${report_file}"
}

# Show active feedback loops
cmd_loops() {
    log_info "Active Feedback Loops"
    echo "================================"
    
    # Check for saved loops data
    local loops_file="${REPORTS_DIR}/reflexivity_state.json"
    
    if [[ -f "${loops_file}" ]]; then
        log_info "Loading from state file..."
        # In real implementation, parse and display
    fi
    
    # Display sample structure
    echo ""
    echo "POSITIVE FEEDBACK (Self-Reinforcing):"
    echo "  [loop_2330_trend_1234567890] 2330.TW | Trend | 75% | Maturing"
    echo "  [loop_2317_herd_1234567890] 2317.TW | Herding | 62% | Active"
    echo ""
    echo "NEGATIVE FEEDBACK (Self-Correcting):"
    echo "  [loop_2881_contra_1234567890] 2881.TW | Contrarian | 45% | Active"
    echo ""
    
    log_info "Use 'report' for detailed analysis"
}

# Show bias for specific symbol
cmd_bias() {
    local symbol="${1:-}"
    
    if [[ -z "${symbol}" ]]; then
        log_error "Symbol required"
        log_info "Example: $0 bias 2330.TW"
        exit 1
    fi
    
    log_info "Bias analysis for: ${symbol}"
    echo "================================"
    
    # Sample analysis structure
    echo ""
    echo "Current Bias Profile:"
    echo "  Primary Bias: Trend Following"
    echo "  Magnitude: +0.72 (Bullish)"
    echo "  Confidence: 68%"
    echo ""
    echo "Contributing Agents:"
    echo "  - super_druckenmiller: +0.85 (Macro momentum)"
    echo "  - taiwan_macro: +0.45 (General bullish)"
    echo "  - sector_semiconductor: +0.78 (Sector strength)"
    echo ""
    echo "Feedback Loop Status:"
    echo "  Positive feedback detected"
    echo "  Loop Strength: 0.75"
    echo "  Stage: Maturing"
    echo ""
    
    # Check for alerts
    if [[ "${symbol}" == "2330.TW" ]]; then
        log_warning "Elevated bias levels detected"
        log_info "Recommendation: Monitor for exhaustion"
    fi
}

# Check for alerts
cmd_alert() {
    log_info "Checking Reflexivity Alerts..."
    echo "================================"
    
    local alerts_found=0
    
    # Check bubble conditions
    echo ""
    echo "BUBBLE FORMATION CHECK:"
    local bubble_symbols=""
    
    # In real implementation, query reflexivity engine
    # For now, show structure
    if [[ -n "${bubble_symbols}" ]]; then
        log_alert "BUBBLE RISK: ${bubble_symbols}"
        ((alerts_found++))
    else
        echo "  ✓ No bubble formations detected"
    fi
    
    # Check crash conditions
    echo ""
    echo "CRASH/CAPITULATION CHECK:"
    local crash_symbols=""
    
    if [[ -n "${crash_symbols}" ]]; then
        log_alert "CRASH RISK: ${crash_symbols}"
        ((alerts_found++))
    else
        echo "  ✓ No capitulation patterns detected"
    fi
    
    # Check high correlation
    echo ""
    echo "CORRELATION CHECK:"
    echo "  ⚠ Semiconductor sector: High agent correlation (85%)"
    echo "    Recommendation: Consider spawning alternative agent"
    ((alerts_found++))
    
    echo ""
    if [[ ${alerts_found} -eq 0 ]]; then
        log_success "All clear - no critical alerts"
    else
        log_warning "Found ${alerts_found} alerts requiring attention"
        log_info "Run 'report' for detailed analysis"
    fi
}

# Save current state
cmd_save() {
    log_info "Saving Reflexivity Engine State..."
    
    local state_file="${REPORTS_DIR}/reflexivity_state_$(date +%Y%m%d_%H%M%S).json"
    
    cat > "${state_file}" << EOF
{
    "saved_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "feedback_loops": [],
    "biases": {},
    "realities": {},
    "alerts": [],
    "metadata": {
        "version": "1.0",
        "engine": "Soros Reflexivity Engine"
    }
}
EOF

    log_success "State saved: ${state_file}"
}

# Show history
cmd_history() {
    local days="${1:-7}"
    
    log_info "Reflexivity History (last ${days} days)"
    echo "================================"
    
    # Find historical reports
    local reports=$(find "${REPORTS_DIR}" -name "reflexivity_report_*.md" -mtime -${days} 2>/dev/null | sort)
    
    if [[ -z "${reports}" ]]; then
        log_warning "No reports found in last ${days} days"
        return
    fi
    
    echo ""
    echo "Historical Reports:"
    for report in ${reports}; do
        local date=$(basename "${report}" | sed 's/reflexivity_report_//' | sed 's/.md//')
        echo "  - ${date}"
    done
    
    echo ""
    log_info "Trend Analysis:"
    echo "  Bubble Risk Trend: Stable"
    echo "  Crash Risk Trend: Decreasing"
    echo "  Average Active Loops: 3.2"
}

# Daily analysis
cmd_daily() {
    log_info "Running Daily Reflexivity Analysis..."
    echo "================================"
    
    # Generate report
    cmd_report > /dev/null 2>&1
    
    # Check alerts
    cmd_alert
    
    # Save state
    cmd_save > /dev/null 2>&1
    
    # Clean old states (keep 30 days)
    local old_count=$(find "${REPORTS_DIR}" -name "reflexivity_state_*.json" -mtime +30 | wc -l)
    find "${REPORTS_DIR}" -name "reflexivity_state_*.json" -mtime +30 -delete
    log_info "Cleaned ${old_count} old state files"
    
    log_success "Daily analysis complete"
}

# Main
case "${1:-help}" in
    report) cmd_report ;;
    loops) cmd_loops ;;
    bias) cmd_bias "${2:-}" ;;
    alert) cmd_alert ;;
    save) cmd_save ;;
    history) cmd_history "${2:-7}" ;;
    daily) cmd_daily ;;
    help|--help|-h) show_usage ;;
    *)
        echo -e "${RED}Unknown command: ${1}${NC}"
        show_usage
        exit 1
        ;;
esac
