package config

import (
	"math"
)

func defaultNarrativeParameters() NarrativeParameters {
	return NarrativeParameters{
		MinTrendStrength: ParameterMetadata[float64]{
			Value:     0.7,
			Rationale: "Minimum trend strength (0-1) to be considered significant for structural override",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [0.5, 0.8] range",
		},
		MinConfidence: ParameterMetadata[float64]{
			Value:     0.75,
			Rationale: "Minimum confidence level for structural trend detection",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [0.6, 0.85] range",
		},
		MinHitRate: ParameterMetadata[float64]{
			Value:     0.70,
			Rationale: "Minimum historical hit rate for structural trend validity",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [0.6, 0.8] range",
		},
		OverrideThreshold: ParameterMetadata[float64]{
			Value:     0.65,
			Rationale: "Score threshold for structural trends to override macro risk signals",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [0.55, 0.75] range",
		},
		AIRevenueGrowthThreshold: ParameterMetadata[float64]{
			Value:     50.0,
			Rationale: "AI revenue YoY growth % threshold to detect AI capex surge (TSMC revenue proxy)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical TSMC revenue data",
		},
		CoWoSUtilizationThreshold: ParameterMetadata[float64]{
			Value:     85.0,
			Rationale: "CoWoS capacity utilization % threshold indicating structural AI demand",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from CoWoS utilization reports",
		},
		CapexGrowthThreshold: ParameterMetadata[float64]{
			Value:     25.0,
			Rationale: "25% YoY capex growth threshold for AI infrastructure expansion (captures early-cycle)",
			Source:    SourceHeuristic,
		},
		US10YChangeBpsThreshold: ParameterMetadata[float64]{
			Value:     10.0,
			Rationale: "US 10Y yield change in basis points to trigger US_rates_up event",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical yield volatility distribution",
		},
		DXYChangePctThreshold: ParameterMetadata[float64]{
			Value:     1.5,
			Rationale: "DXY change % threshold to trigger US_rates_up event alongside yield move",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical DXY distribution",
		},
		GeopoliticalGPRThreshold: ParameterMetadata[float64]{
			Value:     150.0,
			Rationale: "Geopolitical risk index (GPR) threshold to trigger geopolitical_risk_spike event",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from Caldara-Iacoviello GPR index historical data",
		},
		OilChangePctThreshold: ParameterMetadata[float64]{
			Value:     5.0,
			Rationale: "Oil price change % threshold (absolute) to trigger oil_price_shock event",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical oil price volatility",
		},
		JPYChangePctThreshold: ParameterMetadata[float64]{
			Value:     2.0,
			Rationale: "JPY change % threshold to trigger JPY_carry_unwind event",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical JPY volatility around BOJ policy shifts",
		},
		VIXLevelThreshold: ParameterMetadata[float64]{
			Value:     25.0,
			Rationale: "VIX level threshold to trigger JPY_carry_unwind and geopolitical events",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical VIX distribution around crisis periods",
		},
		TaiwanStressDXYWeight: ParameterMetadata[float64]{
			Value:     0.13,
			Rationale: "DXY component weight in Taiwan stress index (13%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: DXY vs foreign flow correlation",
		},
		TaiwanStressUS10YWeight: ParameterMetadata[float64]{
			Value:     0.18,
			Rationale: "US 10Y yield component weight in Taiwan stress index (18%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: US10Y vs foreign flow correlation",
		},
		TaiwanStressForeignWeight: ParameterMetadata[float64]{
			Value:     0.22,
			Rationale: "Foreign investor net flow component weight in Taiwan stress index (22%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: foreign flow vs TAIEX returns",
		},
		TaiwanStressVIXWeight: ParameterMetadata[float64]{
			Value:     0.13,
			Rationale: "VIX component weight in Taiwan stress index (13%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: VIX vs foreign flow correlation",
		},
		TaiwanStressJPYWeight: ParameterMetadata[float64]{
			Value:     0.08,
			Rationale: "JPY component weight in Taiwan stress index (8%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: JPY vs carry trade flow",
		},
		TaiwanStressGeoWeight: ParameterMetadata[float64]{
			Value:     0.13,
			Rationale: "Geopolitical risk component weight in Taiwan stress index (13%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: GPR vs TAIEX returns",
		},
		TaiwanStressOilWeight: ParameterMetadata[float64]{
			Value:     0.07,
			Rationale: "Oil price component weight in Taiwan stress index (7%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: oil price vs foreign flow correlation",
		},
		TaiwanStressGoldWeight: ParameterMetadata[float64]{
			Value:     0.06,
			Rationale: "Gold price component weight in Taiwan stress index (6%)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from regression: gold price vs foreign flow correlation",
		},
		TaiwanStressDXYScale: ParameterMetadata[float64]{
			Value:     5.0,
			Rationale: "DXY change (%) scaling: 1% change = 5 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressUS10YScale: ParameterMetadata[float64]{
			Value:     2.0,
			Rationale: "US10Y yield scaling: 1% yield = 2 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressForeignScale: ParameterMetadata[float64]{
			Value:     10.0,
			Rationale: "Foreign flow scaling: 1B TWD outflow = 10 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressVIXScale: ParameterMetadata[float64]{
			Value:     2.5,
			Rationale: "VIX scaling: VIX=40 maps to 100 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressJPYScale: ParameterMetadata[float64]{
			Value:     10.0,
			Rationale: "JPY change (%) scaling: 1% change = 10 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressGeoScale: ParameterMetadata[float64]{
			Value:     1.0,
			Rationale: "Geopolitical score scaling: direct pass-through (already 0-100)",
			Source:    SourceHeuristic,
		},
		TaiwanStressOilScale: ParameterMetadata[float64]{
			Value:     2.0,
			Rationale: "Oil change (%) scaling: 1% change = 2 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressGoldScale: ParameterMetadata[float64]{
			Value:     2.0,
			Rationale: "Gold change (%) scaling: 1% change = 2 stress points",
			Source:    SourceHeuristic,
		},
		TaiwanStressCrisisThreshold: ParameterMetadata[float64]{
			Value:     70.0,
			Rationale: "Crisis regime threshold (red alert)",
			Source:    SourceHeuristic,
		},
		TaiwanStressHighThreshold: ParameterMetadata[float64]{
			Value:     50.0,
			Rationale: "High stress regime threshold (orange alert)",
			Source:    SourceHeuristic,
		},
		TaiwanStressAlertThreshold: ParameterMetadata[float64]{
			Value:     30.0,
			Rationale: "Alert regime threshold (yellow alert)",
			Source:    SourceHeuristic,
		},
		CalibrationBaselineWindow: ParameterMetadata[int]{
			Value:     60,
			Rationale: "60 trading days ≈ 3 calendar months for rolling baseline; long enough to span a full seasonal cycle, short enough to remain market-relevant",
			Source:    SourceHeuristic,
			Todo:      "re-evaluate window after 6 months of live calibration data",
		},
		CalibrationTargetMedian: ParameterMetadata[float64]{
			Value:     20.0,
			Rationale: "target 20 points per factor under normal conditions; keeps the Taiwan Stress Index within the 0-100 range while allowing headroom for stress spikes",
			Source:    SourceHeuristic,
		},
		CalibrationValidationPct: ParameterMetadata[float64]{
			Value:     0.2,
			Rationale: "standard 80/20 train/validation split; validation set is used to detect out-of-sample degradation before export",
			Source:    SourceHeuristic,
		},
		CalibrationMinRecords: ParameterMetadata[int]{
			Value:     10,
			Rationale: "minimum 10 historical records to attempt calibration; below this, statistical significance is too low to trust the new config",
			Source:    SourceHeuristic,
		},
		CalibrationEnabled: ParameterMetadata[bool]{
			Value:     false,
			Rationale: "disabled by default; enable after initial validation confirms improvement over hand-tuned config",
			Source:    SourceHeuristic,
		},
		EventTTLMultiplier: ParameterMetadata[map[string]float64]{
			Value: map[string]float64{
				"AI_capex_surge":          90,
				"US_rates_up":             7,
				"JPY_carry_unwind":        14,
				"geopolitical_risk_spike": 30,
				"oil_price_shock":         15,
				"Fed_emergency_cut":       3,
				"earnings_surprise":       10,
			},
			Rationale: "Event TTL in days per theme: AI capex 90d (structural), rates 7d (transient), carry unwind 14d, geopolitical 30d, oil 15d, Fed emergency 3d, earnings 10d",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical event impact decay analysis",
		},
		ModelLookbackDays: ParameterMetadata[int]{
			Value:     10,
			Rationale: "Lookback window in trading days for model evaluation",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [5, 20] range",
		},
		ModelHoldWindowDays: ParameterMetadata[int]{
			Value:     5,
			Rationale: "Forward hold window in trading days for model evaluation",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [3, 10] range",
		},
		RetailFrenzyPercentileThreshold: ParameterMetadata[float64]{
			Value:     90.0,
			Rationale: "Margin balance percentile threshold for retail frenzy event; >=90th percentile indicates extreme retail buying",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical margin balance distribution during retail-driven rallies",
		},
		RetailFearPercentileThreshold: ParameterMetadata[float64]{
			Value:     10.0,
			Rationale: "Margin balance percentile threshold for retail fear event; <=10th percentile indicates extreme retail selling",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical margin balance distribution during retail-driven selloffs",
		},
		RetailAccelerationWindowDays: ParameterMetadata[int]{
			Value:     5,
			Rationale: "Rolling acceleration window in trading days for retail margin velocity confirmation",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from backtest: test [3, 10] range for optimal retail momentum detection",
		},
		InflationEstimate: ParameterMetadata[float64]{
			Value:     2.5,
			Rationale: "long-run US inflation target used as fallback when live CPI data is unavailable",
			Source:    "heuristic",
			Todo:      "replace with live CPI from FRED API when available",
		},
		SpringFestivalConfidence: ParameterMetadata[float64]{
			Value:     0.65,
			Rationale: "Confidence for spring festival seasonal event (Jan 15 - Feb 15); based on historical TWSE pre/post-CNY rally probability ~70%",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TWSE historical CNY window returns and hit rate",
		},
		ElectionCycleConfidence: ParameterMetadata[float64]{
			Value:     0.60,
			Rationale: "Confidence for election cycle seasonal event (late Dec - mid Jan); based on pre-election uncertainty premium",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TWSE historical election cycle returns",
		},
		EarningsBlackoutConfidence: ParameterMetadata[float64]{
			Value:     0.55,
			Rationale: "Confidence for earnings blackout seasonal event (Mar 1 - Apr 15); moderate pre-earnings positioning signal",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TWSE historical blackout period returns",
		},
		TechPeakSeasonConfidence: ParameterMetadata[float64]{
			Value:     0.75,
			Rationale: "Confidence for tech peak season event (Jul 1 - Sep 15); strong historical signal driven by back-to-school and holiday demand",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TWSE historical Q3 tech sector returns",
		},
		YearEndWindowDressingConfidence: ParameterMetadata[float64]{
			Value:     0.58,
			Rationale: "Confidence for year-end window dressing event (Nov - Dec); institutional rebalancing effect",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TWSE historical year-end returns and institutional flow patterns",
		},
		EarningsSurpriseConfidence: ParameterMetadata[float64]{
			Value:     0.65,
			Rationale: "Confidence baseline for externally-triggered earnings surprise events (consumed by ingestor detectors, not calendar-based); default before empirical calibration",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from earnings surprise frequency and market reaction data",
		},
		EarningsSurpriseThreshold: ParameterMetadata[float64]{
			Value:     15.0,
			Rationale: "TSMC revenue YoY change %% threshold to trigger earnings_surprise event; 15%% represents 2+ standard deviations above mean quarterly revenue growth",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TSMC historical quarterly revenue surprise distribution",
		},
		GoldChangePctThreshold: ParameterMetadata[float64]{
			Value:     2.0,
			Rationale: "Gold price change %% threshold for geopolitical risk detection; gold traditionally serves as safe-haven proxy",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical gold volatility around geopolitical events",
		},
		USDTWDChangePctThreshold: ParameterMetadata[float64]{
			Value:     1.0,
			Rationale: "USD/TWD daily change %% threshold for FX volatility event; 1%% daily move is significant for managed-float TWD",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical USD/TWD daily volatility distribution",
		},
		SemiconductorExportDropThreshold: ParameterMetadata[float64]{
			Value:     -5.0,
			Rationale: "Semiconductor export change %% threshold for downturn detection; -5%% MoM decline signals demand weakening",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical Taiwan electronics export cycles",
		},
		RetailMarginZScoreThreshold: ParameterMetadata[float64]{
			Value:     1.5,
			Rationale: "Margin balance z-score threshold for retail divergence event; z>1.5 indicates extreme positioning",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical margin balance distribution",
		},
		AICapexSentimentThreshold: ParameterMetadata[float64]{
			Value:     0.5,
			Rationale: "AI capex sentiment score threshold for AI_capex_surge event; >0.5 indicates bullish capex outlook",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TSMC capex guidance vs forward returns",
		},
		TSMCRevenueYoYThreshold: ParameterMetadata[float64]{
			Value:     10.0,
			Rationale: "TSMC revenue YoY growth %% threshold for AI sentiment computation; >10%% indicates strong AI demand",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TSMC quarterly revenue cycles",
		},
		TaiwanStressUSDTWDThreshold: ParameterMetadata[float64]{
			Value:     1.0,
			Rationale: "USD/TWD change %% threshold for Taiwan stress signal in geopolitical detection; 1%% depreciation signals capital outflow",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical TWD depreciation episodes",
		},
		RetailInstitutionalDivergenceThreshold: ParameterMetadata[float64]{
			Value:     0.0,
			Rationale: "Retail-institutional divergence threshold; divergence > 0 means retail is more bullish than institutions",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from divergence index backtest",
		},
		AICapexNegativeSentimentThreshold: ParameterMetadata[float64]{
			Value:     -0.3,
			Rationale: "AI capex sentiment threshold for semiconductor downturn detection; <-0.3 indicates bearish outlook",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical sentiment floor levels",
		},
		AICapexFallbackSentiment: ParameterMetadata[float64]{
			Value:     -0.3,
			Rationale: "Fallback AI capex sentiment when TSMC revenue YoY is not positive; conservative bearish default",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical TSMC revenue-to-sentiment mapping",
		},
		TSMCRevenuePositiveThreshold: ParameterMetadata[float64]{
			Value:     0.0,
			Rationale: "TSMC revenue YoY threshold for positive growth; >0%% triggers moderate bullish sentiment",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from TSMC revenue growth distribution",
		},
		ConfidenceBaseUSRates: ParameterMetadata[float64]{
			Value:     0.75,
			Rationale: "Base confidence for US rates event; derived from historical predictability of yield-driven episodes",
			Source:    SourceEmpirical,
			Todo:      "Recalibrate when significant Fed regime change occurs",
		},
		ConfidenceBaseJPYCarry: ParameterMetadata[float64]{
			Value:     0.65,
			Rationale: "Base confidence for JPY carry unwind event; derived from carry trade unwinding historical patterns",
			Source:    SourceEmpirical,
			Todo:      "Recalibrate after major BOJ policy shifts",
		},
		ConfidenceBaseGeopolitical: ParameterMetadata[float64]{
			Value:     0.65,
			Rationale: "Base confidence for geopolitical risk event; derived from GPR index historical correlations",
			Source:    SourceEmpirical,
			Todo:      "Recalibrate when GPR index methodology changes",
		},
		ConfidenceBaseOilShock: ParameterMetadata[float64]{
			Value:     0.60,
			Rationale: "Base confidence for oil price shock event; derived from Hamilton-type oil shock literature",
			Source:    SourceEmpirical,
			Todo:      "Recalibrate with structural oil market changes",
		},
		ConfidenceBaseAICapex: ParameterMetadata[float64]{
			Value:     0.70,
			Rationale: "Base confidence for AI capex event; derived from TSMC capex guidance vs semiconductor cycle correlation",
			Source:    SourceEmpirical,
			Todo:      "Recalibrate as AI capex cycle data accumulates",
		},
		ConfidenceBaseTSMCRevenue: ParameterMetadata[float64]{
			Value:     0.70,
			Rationale: "Base confidence for TSMC revenue-based events; derived from WSTS semiconductor forecast accuracy",
			Source:    SourceEmpirical,
			Todo:      "Recalibrate as TSMC revenue data accumulates",
		},
		ConfidenceBaseTaiwanStress: ParameterMetadata[float64]{
			Value:     0.60,
			Rationale: "Base confidence for Taiwan stress index-based events; conservative heuristic default",
			Source:    SourceHeuristic,
			Todo:      "Calibrate from historical Taiwan stress index distribution",
		},
		ConfidenceDeviationCeiling: ParameterMetadata[float64]{
			Value:     0.95,
			Rationale: "Upper bound for deviation-based dynamic confidence; prevents perfect certainty (1.0) for any single indicator",
			Source:    SourceHeuristic,
			Todo:      "Backtest optimal ceiling against forward returns; consider per-theme ceilings",
		},
		SOXIndexDropThreshold: ParameterMetadata[float64]{
			Value:     -5.0,
			Rationale: "SOX index change %% threshold for semiconductor stress detection; -5%% is significant drawdown",
			Source:    SourceEmpirical,
			Todo:      "Calibrate from historical SOX index volatility",
		},
	}
}

func defaultJanusParameters() JanusParameters {
	return JanusParameters{
		ShortWindowDays: ParameterMetadata[int]{
			Value:     5,
			Rationale: "Short lookback window (~1 trading week) for cohort performance",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [3, 10] range for short-term sensitivity",
		},
		MediumWindowDays: ParameterMetadata[int]{
			Value:     20,
			Rationale: "Medium lookback window (~1 trading month) for cohort performance",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [15, 30] range for medium-term stability",
		},
		LongWindowDays: ParameterMetadata[int]{
			Value:     60,
			Rationale: "Long lookback window (~1 trading quarter) for cohort performance",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [40, 90] range for long-term memory",
		},
		MaxHistoryDays: ParameterMetadata[int]{
			Value:     90,
			Rationale: "Maximum rolling history per cohort; must cover longest window comfortably",
			Source:    SourceHeuristic,
		},
		MinWeight: ParameterMetadata[float64]{
			Value:     0.05,
			Rationale: "Floor for any cohort weight; prevents total elimination",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.01, 0.10] range",
		},
		MaxWeight: ParameterMetadata[float64]{
			Value:     0.60,
			Rationale: "Ceiling for any cohort weight; prevents single-cohort dominance",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.40, 0.80] range",
		},
		NovelThreshold: ParameterMetadata[float64]{
			Value:     0.15,
			Rationale: "Weight delta threshold for NOVEL_REGIME detection; short-window winner surges past long-window standing",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.10, 0.25] range",
		},
		HistoricalThreshold: ParameterMetadata[float64]{
			Value:     0.15,
			Rationale: "Weight delta threshold for HISTORICAL_REGIME detection; long-window winner maintains stable lead",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.10, 0.25] range",
		},
		EpsilonWeight: ParameterMetadata[float64]{
			Value:     0.02,
			Rationale: "Minimal weight assigned to negative-Sharpe cohorts when others are positive",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.01, 0.05] range",
		},
		ShortWindowBlend: ParameterMetadata[float64]{
			Value:     0.5,
			Rationale: "50% weight on short-window Sharpe in blended score; emphasizes recent accuracy",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.3, 0.6] range; must sum with medium+long to 1.0",
		},
		MediumWindowBlend: ParameterMetadata[float64]{
			Value:     0.3,
			Rationale: "30% weight on medium-window Sharpe in blended score",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.2, 0.4] range; must sum with short+long to 1.0",
		},
		LongWindowBlend: ParameterMetadata[float64]{
			Value:     0.2,
			Rationale: "20% weight on long-window Sharpe in blended score; retains long-term memory",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.1, 0.3] range; must sum with short+medium to 1.0",
		},
		HealthStaleHours: ParameterMetadata[int]{
			Value:     168,
			Rationale: "Hours before JANUS data is considered stale (7 days); triggers error-level health alert",
			Source:    SourceHeuristic,
		},
		HealthWarnHours: ParameterMetadata[int]{
			Value:     48,
			Rationale: "Hours before JANUS data triggers warning-level health alert (2 days)",
			Source:    SourceHeuristic,
		},
	}
}

func defaultIndustryParameters() IndustryParameters {
	return IndustryParameters{
		CycleThresholds: ParameterMetadata[map[string]CycleThresholdConfig]{
			Value: map[string]CycleThresholdConfig{
				"_default": {
					ExpansionRevenuePct: 0.20,
					ExpansionProfitPct:  0.20,
					RecoveryRevenuePct:  0.05,
					RecoveryProfitPct:   0.05,
					MatureRevenuePct:    -0.05,
					MatureProfitPct:     -0.05,
				},
				"semiconductor": {
					ExpansionRevenuePct: 0.20,
					ExpansionProfitPct:  0.25,
					RecoveryRevenuePct:  0.10,
					RecoveryProfitPct:   0.15,
					MatureRevenuePct:    0.05,
					MatureProfitPct:     0.08,
				},
				"financials": {
					ExpansionRevenuePct: 0.10,
					ExpansionProfitPct:  0.15,
					RecoveryRevenuePct:  0.05,
					RecoveryProfitPct:   0.08,
					MatureRevenuePct:    0.02,
					MatureProfitPct:     0.05,
				},
				"shipping": {
					ExpansionRevenuePct: 0.30,
					ExpansionProfitPct:  0.35,
					RecoveryRevenuePct:  0.15,
					RecoveryProfitPct:   0.20,
					MatureRevenuePct:    0.05,
					MatureProfitPct:     0.10,
				},
				"electronics": {
					ExpansionRevenuePct: 0.15,
					ExpansionProfitPct:  0.18,
					RecoveryRevenuePct:  0.08,
					RecoveryProfitPct:   0.10,
					MatureRevenuePct:    0.03,
					MatureProfitPct:     0.05,
				},
				"ai_supply_chain": {
					ExpansionRevenuePct: 0.25,
					ExpansionProfitPct:  0.30,
					RecoveryRevenuePct:  0.12,
					RecoveryProfitPct:   0.15,
					MatureRevenuePct:    0.05,
					MatureProfitPct:     0.08,
				},
				"industrial": {
					ExpansionRevenuePct: 0.12,
					ExpansionProfitPct:  0.15,
					RecoveryRevenuePct:  0.05,
					RecoveryProfitPct:   0.08,
					MatureRevenuePct:    0.00,
					MatureProfitPct:     0.02,
				},
				"energy": {
					ExpansionRevenuePct: 0.10,
					ExpansionProfitPct:  0.12,
					RecoveryRevenuePct:  0.04,
					RecoveryProfitPct:   0.06,
					MatureRevenuePct:    0.00,
					MatureProfitPct:     0.02,
				},
				"consumer": {
					ExpansionRevenuePct: 0.08,
					ExpansionProfitPct:  0.10,
					RecoveryRevenuePct:  0.03,
					RecoveryProfitPct:   0.05,
					MatureRevenuePct:    -0.02,
					MatureProfitPct:     0.00,
				},
				"robotics": {
					ExpansionRevenuePct: 0.20,
					ExpansionProfitPct:  0.22,
					RecoveryRevenuePct:  0.08,
					RecoveryProfitPct:   0.10,
					MatureRevenuePct:    0.02,
					MatureProfitPct:     0.05,
				},
				"mining": {
					ExpansionRevenuePct: 0.25,
					ExpansionProfitPct:  0.28,
					RecoveryRevenuePct:  0.10,
					RecoveryProfitPct:   0.12,
					MatureRevenuePct:    0.02,
					MatureProfitPct:     0.05,
				},
				"leo_satellite": {
					ExpansionRevenuePct: 0.22,
					ExpansionProfitPct:  0.25,
					RecoveryRevenuePct:  0.10,
					RecoveryProfitPct:   0.12,
					MatureRevenuePct:    0.03,
					MatureProfitPct:     0.05,
				},
				"etf_rotation": {
					ExpansionRevenuePct: 0.05,
					ExpansionProfitPct:  0.05,
					RecoveryRevenuePct:  0.02,
					RecoveryProfitPct:   0.02,
					MatureRevenuePct:    -0.02,
					MatureProfitPct:     -0.02,
				},
			},
			Rationale: "Per-industry business cycle thresholds covering all 12 L1 sectors. _default key serves as fallback for L2/L3 segments without explicit config. Thresholds calibrated by cyclicality: high-cyclical (shipping, mining) > growth (semiconductor, AI) > stable (financials, energy) > defensive (consumer).",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive from historical revenue/profit CAGR per sector via cmd/calibrate-seasonal --cycle-thresholds. Auto-update after each quarterly earnings season.",
		},
		InventoryCycleThresholds: ParameterMetadata[InventoryCycleThresholdConfig]{
			Value: InventoryCycleThresholdConfig{
				ActiveRestockingInventoryMin:  6.0,
				ActiveRestockingCapacityMin:   0.80,
				PassiveRestockingInventoryMin: 4.0,
				PassiveRestockingCapacityMin:  0.70,
				ActiveDestockingInventoryMax:  3.0,
				ActiveDestockingCapacityMax:   0.60,
			},
			Rationale: "Inventory cycle thresholds derived from TW semiconductor and electronics supply chain behavior",
			Source:    SourceHeuristic,
		},
		CapexCycleThresholds: ParameterMetadata[CapexCycleThresholdConfig]{
			Value: CapexCycleThresholdConfig{
				ExpansionCapacityMin:   0.85,
				ExpansionRevenueMin:    0.15,
				MaintenanceCapacityMin: 0.70,
				MaintenanceRevenueMin:  0.05,
			},
			Rationale: "Capex cycle thresholds: expansion at >85% utilization + >15% revenue growth; maintenance at >70% + >5%",
			Source:    SourceHeuristic,
		},
		ConcentrationRiskEnabled: ParameterMetadata[bool]{
			Value:     true,
			Rationale: "Enable customer concentration risk scoring for supply chain analysis",
			Source:    SourceHeuristic,
		},
		NewsLatencyRiskEnabled: ParameterMetadata[bool]{
			Value:     true,
			Rationale: "Enable news latency risk scoring for event-driven positions",
			Source:    SourceHeuristic,
		},
		AsymmetricRiskEnabled: ParameterMetadata[bool]{
			Value:     true,
			Rationale: "Enable asymmetric downside risk scoring (tail risk analysis)",
			Source:    SourceHeuristic,
		},
		CustomerConcentrationLimit: ParameterMetadata[float64]{
			Value:     0.40,
			Rationale: "Flag customer concentration >40% as high risk; TSMC Apple exposure ~25% is acceptable",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.30, 0.50] range; consider industry norms",
		},
		GeographicExposureLimit: ParameterMetadata[float64]{
			Value:     0.60,
			Rationale: "Flag geographic revenue concentration >60% as high risk; China exposure threshold",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.50, 0.70] range based on geopolitical risk assessment",
		},
		CustomerShareThreshold1: ParameterMetadata[float64]{
			Value:     30.0,
			Rationale: "First tier customer concentration threshold (30%); triggers initial risk score",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [20, 40] range",
		},
		CustomerShareThreshold2: ParameterMetadata[float64]{
			Value:     50.0,
			Rationale: "Second tier customer concentration threshold (50%); triggers higher risk score",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [40, 60] range",
		},
		USExposureThreshold1: ParameterMetadata[float64]{
			Value:     50.0,
			Rationale: "US geographic exposure threshold (50%); triggers initial risk score",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [40, 60] range",
		},
		USExposureThreshold2: ParameterMetadata[float64]{
			Value:     70.0,
			Rationale: "High US geographic exposure threshold (70%); triggers higher risk score",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [60, 80] range",
		},
		RiskScoreWeight1: ParameterMetadata[float64]{
			Value:     0.4,
			Rationale: "Risk score weight for first tier customer concentration",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.2, 0.5] range",
		},
		RiskScoreWeight2: ParameterMetadata[float64]{
			Value:     0.3,
			Rationale: "Risk score weight for second tier customer concentration",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.2, 0.4] range",
		},
		RiskScoreWeight3: ParameterMetadata[float64]{
			Value:     0.2,
			Rationale: "Risk score weight for first tier US exposure",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.1, 0.3] range",
		},
		RiskScoreWeight4: ParameterMetadata[float64]{
			Value:     0.1,
			Rationale: "Risk score weight for second tier US exposure",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.05, 0.2] range",
		},
		SeverityThresholdMedium: ParameterMetadata[float64]{
			Value:     0.4,
			Rationale: "Risk score threshold for medium severity",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.3, 0.5] range",
		},
		SeverityThresholdHigh: ParameterMetadata[float64]{
			Value:     0.6,
			Rationale: "Risk score threshold for high severity",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.5, 0.7] range",
		},
		SeverityThresholdCritical: ParameterMetadata[float64]{
			Value:     0.8,
			Rationale: "Risk score threshold for critical severity",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.7, 0.9] range",
		},
		ImpactMultiplier: ParameterMetadata[float64]{
			Value:     0.15,
			Rationale: "Multiplier for estimated price impact from risk score",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.10, 0.25] range",
		},
		RiskConfidence: ParameterMetadata[float64]{
			Value:     0.85,
			Rationale: "Confidence level for risk assessment",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.70, 0.95] range",
		},
		ConfidenceSignal: ParameterMetadata[ConfidenceSignalConfig]{
			Value: ConfidenceSignalConfig{
				SignalBase:               0.30,
				RevenueNormDenom:         0.50,
				RevenueWeight:            0.25,
				ProfitNormDenom:          0.50,
				ProfitWeight:             0.25,
				InventoryNormDenom:       10.0,
				InventoryWeight:          0.10,
				UtilizationWeight:        0.15,
				SignalBoundaryMix:        0.60,
				BoundaryDenomFactor:      0.30,
				ConfidenceFloor:          0.10,
				ConfidenceCeiling:        1.00,
				RevenueTrendThreshold:    0.10,
				RevenueIndicatorWeight:   0.30,
				InventoryTrendThreshold:  4.0,
				InventoryIndicatorWeight: 0.25,
				ProfitTrendThreshold:     0.10,
				ProfitIndicatorWeight:    0.35,
				CapacityTrendThreshold:   0.75,
				CapacityIndicatorWeight:  0.30,
				TrendUpMultiplier:        1.1,
				TrendDownMultiplier:      0.9,
				ThresholdRangeFallback:   0.25,
			},
			Rationale: "Signal weights derived from relative informativeness of each metric; boundary denom based on threshold spread; mix ratio balances data amplitude vs phase clarity",
			Source:    SourceHeuristic,
		},
		ConfidenceMix: ParameterMetadata[ConfidenceMixConfig]{
			Value: ConfidenceMixConfig{
				WeightBoundary:         0.45,
				WeightFreshness:        0.20,
				WeightSeasonal:         0.15,
				WeightLinkage:          0.10,
				WeightNarrative:        0.1,
				FavorableConfidenceMin: 0.4,
			},
			Rationale: "Confidence mix: boundary(45%) + freshness(20%) + seasonal(15%) + linkage(10%) + narrative(10%)",
			Source:    SourceHeuristic,
		},
		SeasonalPatterns: ParameterMetadata[[]SeasonalPatternConfig]{
			Value: []SeasonalPatternConfig{
				{
					ID: "spring_festival", Name: "春節行情", NameEN: "Spring Festival Rally",
					StartMonth: 1, StartDay: 15, EndMonth: 2, EndDay: 15,
					FavoredIndustries: []string{"financials"}, AvoidedIndustries: []string{"semiconductor", "ai_supply_chain"},
					StyleTags:        []string{"high_dividend", "small_cap"},
					AdjustmentFactor: 1.15, HistoricalAccuracy: 0.70, AvgMarketReturn: 0.032,
					Description: "年前資金回籠，高股息與金融股受追捧；電子股進入淡季",
				},
				{
					ID: "earnings_window", Name: "季報空窗期", NameEN: "Earnings Report Window",
					StartMonth: 3, StartDay: 1, EndMonth: 4, EndDay: 15,
					FavoredIndustries: []string{"ai_supply_chain", "electronics"}, AvoidedIndustries: []string{"consumer", "industrial"},
					AdjustmentFactor: 1.10, HistoricalAccuracy: 0.55, AvgMarketReturn: 0.015,
					Description: "季報空窗期，成長股與AI供應鏈有表現空間",
				},
				{
					ID: "dividend_season", Name: "除權除息季", NameEN: "Dividend Season",
					StartMonth: 5, StartDay: 1, EndMonth: 6, EndDay: 30,
					FavoredIndustries: []string{"financials", "consumer"}, AvoidedIndustries: []string{"semiconductor", "ai_supply_chain", "electronics"},
					StyleTags:        []string{"high_dividend"},
					AdjustmentFactor: 1.20, HistoricalAccuracy: 0.65, AvgMarketReturn: 0.025,
					Description: "除權除息旺季，高股息股與金融股表現較佳；科技股相對弱勢",
				},
				{
					ID: "tech_peak_season", Name: "科技旺季", NameEN: "Technology Peak Season",
					StartMonth: 7, StartDay: 1, EndMonth: 9, EndDay: 15,
					FavoredIndustries: []string{"semiconductor", "ai_supply_chain", "electronics"}, AvoidedIndustries: []string{"consumer"},
					AdjustmentFactor: 1.25, HistoricalAccuracy: 0.75, AvgMarketReturn: 0.085,
					Description: "蘋果新機拉貨、AI晶片需求高峰，科技股表現最強",
				},
				{
					ID: "earnings_verification", Name: "季報驗證期", NameEN: "Earnings Verification",
					StartMonth: 9, StartDay: 15, EndMonth: 10, EndDay: 31,
					AdjustmentFactor: 1.10, HistoricalAccuracy: 0.60, AvgMarketReturn: 0.020,
					Description: "季報公布，獲利優於預期股受追捧，低於預期股遭拋售",
				},
				{
					ID: "year_end_rally", Name: "年底作帳", NameEN: "Year-End Window Dressing",
					StartMonth: 11, StartDay: 1, EndMonth: 12, EndDay: 31,
					FavoredIndustries: []string{"financials"}, StyleTags: []string{"large_cap", "index_heavyweights"},
					AdjustmentFactor: 1.12, HistoricalAccuracy: 0.58, AvgMarketReturn: 0.018,
					Description: "法人年底作帳，大型權值股與金融股相對強勢",
				},
				{
					ID: "summer_electricity", Name: "夏季用電高峰", NameEN: "Summer Electricity Peak",
					StartMonth: 6, StartDay: 1, EndMonth: 8, EndDay: 31,
					FavoredIndustries: []string{"energy"}, AvoidedIndustries: []string{"industrial"},
					AdjustmentFactor: 1.08, HistoricalAccuracy: 0.62, AvgMarketReturn: 0.012,
					Description: "夏季用電高峰，能源相對強勢；高耗電製造業成本上升",
				},
				{
					ID: "election_local", Name: "地方選舉行情", NameEN: "Local Election Rally",
					StartMonth: 11, StartDay: 1, EndMonth: 12, EndDay: 5,
					FavoredIndustries: []string{"financials", "construction", "consumer"}, AvoidedIndustries: []string{"semiconductor", "electronics"},
					AdjustmentFactor: 1.10, HistoricalAccuracy: 0.60, AvgMarketReturn: 0.020,
					Description: "地方選舉選前政策護盤，金融營建內需股受惠；科技股相對觀望。證據強度：地方選舉選前 40-20 日上漲機率 86%（富邦研究）",
				},
				{
					ID: "election_presidential", Name: "總統大選行情", NameEN: "Presidential Election Rally",
					StartMonth: 1, StartDay: 1, EndMonth: 2, EndDay: 15,
					FavoredIndustries: []string{"financials", "consumer", "defensive"}, AvoidedIndustries: []string{"semiconductor", "electronics"},
					AdjustmentFactor: 1.08, HistoricalAccuracy: 0.55, AvgMarketReturn: 0.015,
					Description: "總統大選前後政策不確定性，內需防禦型受追捧；科技出口股觀望。證據強度：總統大選前後報酬不一致（MacroMicro），國際情勢影響大於選舉本身",
				},
			},
			Rationale: "9 canonical Taiwan seasonal patterns (7 core + 2 election) from DefaultSeasonalPatterns(); values read from config by NewSeasonalEngine()",
			Source:    SourceHeuristic,
		},
		AsymmetricRisk: ParameterMetadata[AsymmetricRiskConfig]{
			Value: AsymmetricRiskConfig{
				BadNewsThreshold:      -0.03,
				GoodNewsThreshold:     0.05,
				ReactionTimeMinutes:   30,
				VolumeSpikeMultiplier: 2.0,
			},
			Rationale: "3% drop triggers bad news detection; 5% rise for good news; 30 min reaction window; 2x volume confirms",
			Source:    SourceHeuristic,
		},
		NewsLatencyRisk: ParameterMetadata[NewsLatencyConfig]{
			Value: NewsLatencyConfig{
				MaxLatencyHours:       24.0,
				SeverityCriticalMin:   0.8,
				SeverityHighMin:       0.5,
				ImpactMultiplier:      0.05,
				DropCriticalThreshold: 0.10,
				DropHighThreshold:     0.07,
				DropMediumThreshold:   0.05,
				ConfidenceDivisor:     3.0,
			},
			Rationale: "24h max latency gap; severity bands at 0.5/0.8; drop thresholds at 5%/7%/10%",
			Source:    SourceHeuristic,
		},
		AsymmetricDropCritical: ParameterMetadata[float64]{
			Value:     0.10,
			Rationale: "10% price drop triggers critical asymmetric risk severity; aligns with historical TW stock tail-event thresholds where >10% single-day drops correlate with structural deterioration",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive from TWSE historical single-day drawdown distribution (99th percentile)",
		},
		AsymmetricDropHigh: ParameterMetadata[float64]{
			Value:     0.07,
			Rationale: "7% price drop triggers high asymmetric risk severity; captures significant but non-extreme downside moves (e.g., sector-wide selloffs, geopolitical events)",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive from TWSE historical single-day drawdown distribution (95th percentile)",
		},
		AsymmetricDropMedium: ParameterMetadata[float64]{
			Value:     0.05,
			Rationale: "5% price drop triggers medium asymmetric risk severity; captures moderate downside moves that still warrant stop-loss monitoring",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive from TWSE historical single-day drawdown distribution (90th percentile)",
		},
		NewsImpactMultiplier: ParameterMetadata[float64]{
			Value:     0.05,
			Rationale: "5% estimated price impact multiplier for news latency risk scoring; represents conservative estimate of information disadvantage cost for TW investors vs US Tier-1 sources",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive from TW stock price response to delayed news versus US peers (event study methodology)",
		},
		BoundaryFallback: ParameterMetadata[float64]{
			Value:     0.25,
			Rationale: "Fallback threshold range width (25%) when cycle phase thresholds (expansion - mature) produce a non-positive range; prevents division-by-zero in boundary confidence calculation",
			Source:    SourceHeuristic,
			Todo:      "Audit: verify this fallback is rarely triggered once per-industry thresholds are properly calibrated",
		},
		AdjustmentFloor: ParameterMetadata[float64]{
			Value:     0.01,
			Rationale: "Minimum seasonal adjustment floor (1% of baseline); prevents complete elimination of industry weighting when combined adjustments drop below zero",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: test [0.005, 0.02] range for floor impact on portfolio stability",
		},
		FreshnessScores: ParameterMetadata[FreshnessScoresConfig]{
			Value: FreshnessScoresConfig{
				ScoreLive: 1.0, ScoreRecent: 0.8, ScoreStale: 0.4,
				ScoreFallback: 0.2, ScoreDefault: 0.3,
			},
			Rationale: "Maps DataFreshness enum to confidence weights",
			Source:    SourceHeuristic,
		},
		PhaseScores: ParameterMetadata[PhaseScoresConfig]{
			Value: PhaseScoresConfig{
				ScoreExpansion: 20, ScoreRecovery: 10, ScoreMature: 0, ScoreRecession: -20,
			},
			Rationale: "Cycle phase conviction deltas; expansion (+20) and recovery (+10) boost, recession (-20) penalizes, mature (0) neutral",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive phase deltas from sector-regime conviction regression",
		},
		SkillToIndustry: ParameterMetadata[map[string]string]{
			Value: map[string]string{
				"semiconductor_desk": "semiconductor",
				"ai_infrastructure":  "ai_supply_chain",
				"macro_research":     "financials",
				"shipping_analyst":   "shipping",
				"energy_analyst":     "renewable_energy",
				"defense_industrial": "ai_supply_chain",
				"consumer_analyst":   "traditional",
			},
			Rationale: "Maps agent skills to industry sectors for cycle-aware conviction adjustments",
			Source:    SourceHeuristic,
			Todo:      "Validate: verify mapping aligns with sector coverage mandates",
		},
		SkillToIndustries: ParameterMetadata[map[string][]string]{
			Value: map[string][]string{
				"semiconductor_desk":   {"semiconductor", "foundry"},
				"ai_supply_chain_desk": {"ai_supply_chain", "pcb", "thermal"},
				"financials_desk":      {"financials"},
				"shipping_desk":        {"shipping"},
				"leo_satellite_desk":   {"leo_satellite", "satellite_rf_components", "satellite_pcb"},
				"etf_rotation_desk":    {"high_dividend", "etf_rotation"},
			},
			Rationale: "Maps agent skills to one or more industry sectors for sector-ban filtering",
			Source:    SourceHeuristic,
		},
		CycleTransitions: ParameterMetadata[[]CycleTransitionConfig]{
			Value: []CycleTransitionConfig{
				{FromPhase: "recession", ToPhase: "recovery", Triggers: []string{"inventory_depletion", "demand_stabilization"}, Probability: 0.70, TypicalDurationDays: 180},
				{FromPhase: "recovery", ToPhase: "expansion", Triggers: []string{"revenue_acceleration", "capex_increase"}, Probability: 0.80, TypicalDurationDays: 270},
				{FromPhase: "expansion", ToPhase: "mature", Triggers: []string{"growth_deceleration", "margin_compression"}, Probability: 0.60, TypicalDurationDays: 360},
				{FromPhase: "mature", ToPhase: "recession", Triggers: []string{"demand_destruction", "overcapacity"}, Probability: 0.50, TypicalDurationDays: 180},
			},
			Rationale: "TW cycle transition probabilities and durations",
			Source:    SourceHeuristic,
		},
		CycleWeightMultipliers: ParameterMetadata[CycleWeightMultipliersConfig]{
			Value: CycleWeightMultipliersConfig{
				ExpansionMultiplier: 1.2,
				RecoveryMultiplier:  1.1,
				MatureMultiplier:    1.0,
				RecessionMultiplier: 0.7,
			},
			Rationale: "Cycle phase weight multipliers: expansion +20%, recovery +10%, mature neutral, recession -30%",
			Source:    SourceHeuristic,
		},
		LinkageWeightImpact: ParameterMetadata[float64]{
			Value:     0.2,
			Rationale: "Linkage systemic importance deviation scaling: ±20% max impact",
			Source:    SourceHeuristic,
		},
		WeightFloor: ParameterMetadata[float64]{
			Value:     0.03,
			Rationale: "Minimum 3% weight per industry after normalization",
			Source:    SourceHeuristic,
		},
		MaxDailyWeightChange: ParameterMetadata[float64]{
			Value:     0.05,
			Rationale: "Maximum 5% daily weight change to prevent excessive volatility",
			Source:    SourceHeuristic,
		},
		LinkageParams: ParameterMetadata[LinkageConfig]{
			Value: LinkageConfig{
				DownstreamDecayFactor:     0.80,
				UpstreamDecayFactor:       0.60,
				SeasonalDecayFactor:       0.30,
				DefaultCorrelation:        0.50,
				SystemicImportanceDivisor: 10.0,
				MinCorrelationThreshold:   0.30,
				CorrelationWindowDays:     30,
				RecessionCorrelationBoost: 0.30,
				RecessionShockAmplifier:   1.30,
				CorrelationMatrix: map[string]float64{
					"semiconductor ↔ ai_supply_chain": 0.85,
					"semiconductor ↔ electronics":     0.72,
					"semiconductor ↔ robotics":        0.45,
					"semiconductor ↔ financials":      0.15,
					"semiconductor ↔ shipping":        -0.10,
					"ai_supply_chain ↔ electronics":   0.65,
					"ai_supply_chain ↔ robotics":      0.55,
					"ai_supply_chain ↔ financials":    0.20,
					"ai_supply_chain ↔ shipping":      0.05,
					"robotics ↔ electronics":          0.48,
					"robotics ↔ industrial":           0.60,
					"robotics ↔ financials":           0.10,
					"financials ↔ consumer":           0.35,
					"financials ↔ industrial":         0.25,
					"financials ↔ shipping":           0.05,
					"financials ↔ energy":             0.10,
					"shipping ↔ energy":               0.40,
					"shipping ↔ industrial":           0.30,
					"consumer ↔ industrial":           0.20,
					"consumer ↔ energy":               0.15,
					"mining ↔ semiconductor":          0.55,
					"mining ↔ ai_supply_chain":        0.50,
					"mining ↔ electronics":            0.60,
					"mining ↔ robotics":               0.45,
					"mining ↔ industrial":             0.40,
					"mining ↔ energy":                 0.35,
					"mining ↔ financials":             0.30,
					"mining ↔ shipping":               0.25,
					"mining ↔ consumer":               0.10,
					"etf_rotation ↔ financials":       0.45,
					"etf_rotation ↔ semiconductor":    0.30,
					"etf_rotation ↔ shipping":         0.05,
				},
			},
			Rationale: "Downstream decay (0.80) > upstream (0.60); seasonal decay (0.30) for supply-chain propagation; default correlation (0.50); window 30 days; narrative-aware via SeasonalBridge.CorrelationMultiplier() for dynamic macro event modulation. Correlation matrix migrated from hardcoded linkage.go to ParametersConfig.",
			Source:    "heuristic; validated against 2024 TWSE sector index returns",
			Todo:      "Auto-update: run cmd/backfill-correlation-matrix monthly to recompute from TWSE sector index daily returns. Validate: compare matrix against rolling 90-day correlation of sector ETFs.",
		},
		DynamicEnv: ParameterMetadata[DynamicEnvConfig]{
			Value: DynamicEnvConfig{
				OilHighThreshold:       0.10,
				OilLowThreshold:        0.10,
				OilEnergyMult:          0.50,
				OilShippingPenalty:     0.05,
				OilShippingBenefit:     0.05,
				OilIndustrialPenalty:   0.06,
				OilIndustrialBenefit:   0.04,
				BDIHighThreshold:       0.10,
				BDILowThreshold:        0.10,
				BDIShippingBoost:       0.30,
				BDICostPenalty:         0.04,
				DXYHighThreshold:       0.05,
				DXYLowThreshold:        0.03,
				DXYExportPenalty:       0.05,
				DXYExportBenefit:       0.04,
				HistoryWindowDays:      90,
				HistoryCapMultiplier:   2,
				OilPriceShockThreshold: 0.05,
				UsRatesDxyThreshold:    0.03,
				JpyCarryDxyThreshold:   0.03,
			},
			Rationale: "Dynamic env modulation thresholds and multipliers: oil >10% triggers energy/shipping/industrial adjustments; BDI >10% amplifies shipping; DXY >5% penalizes exporters; values preserve original heuristic tuning from dynamic_env.go",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: backtest each multiplier against historical sector returns during macro regime shifts",
		},
		CycleCalibration: ParameterMetadata[CycleCalibrationConfig]{
			Value: CycleCalibrationConfig{
				MinSamples:     10,
				LearningRate:   0.05,
				HitRateHigh:    0.55,
				HitRateLow:     0.45,
				WeightClampMin: 0.05,
				WeightClampMax: 0.40,
				WindowSize:     30,
			},
			Rationale: "Cycle compass self-calibration: min 10 outcome samples before calibration, 5% learning rate for weight adjustments, hit rate >0.55 upweights and <0.45 downweights, weights clamped to [0.05, 0.40] range, 30-session rolling window",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: backtest optimal hit_rate thresholds and learning_rate across multiple TW market regimes",
		},
		HistoryRetentionDays: ParameterMetadata[int]{
			Value:     90,
			Rationale: "Keep 90 days of cycle history for trend analysis",
			Source:    SourceHeuristic,
		},
		DefaultMetrics: ParameterMetadata[map[string]IndustryDefaultMetrics]{
			Value: map[string]IndustryDefaultMetrics{
				"semiconductor":             {RevenueGrowthYoY: 0.25, ProfitGrowthYoY: 0.30, InventoryTurnover: 5.5, CapacityUtilization: 0.85},
				"ai_supply_chain":           {RevenueGrowthYoY: 0.45, ProfitGrowthYoY: 0.50, InventoryTurnover: 6.0, CapacityUtilization: 0.90},
				"robotics":                  {RevenueGrowthYoY: 0.15, ProfitGrowthYoY: 0.12, InventoryTurnover: 4.0, CapacityUtilization: 0.70},
				"financials":                {RevenueGrowthYoY: 0.08, ProfitGrowthYoY: 0.10, InventoryTurnover: 0.0, CapacityUtilization: 0.75},
				"shipping":                  {RevenueGrowthYoY: -0.05, ProfitGrowthYoY: -0.10, InventoryTurnover: 3.0, CapacityUtilization: 0.65},
				"energy":                    {RevenueGrowthYoY: 0.05, ProfitGrowthYoY: 0.03, InventoryTurnover: 4.5, CapacityUtilization: 0.70},
				"electronics":               {RevenueGrowthYoY: 0.12, ProfitGrowthYoY: 0.15, InventoryTurnover: 5.0, CapacityUtilization: 0.75},
				"consumer":                  {RevenueGrowthYoY: 0.03, ProfitGrowthYoY: 0.05, InventoryTurnover: 6.0, CapacityUtilization: 0.70},
				"industrial":                {RevenueGrowthYoY: 0.06, ProfitGrowthYoY: 0.08, InventoryTurnover: 4.0, CapacityUtilization: 0.68},
				"foundry":                   {RevenueGrowthYoY: 0.22, ProfitGrowthYoY: 0.28, InventoryTurnover: 5.0, CapacityUtilization: 0.88},
				"server_assembly":           {RevenueGrowthYoY: 0.40, ProfitGrowthYoY: 0.45, InventoryTurnover: 6.5, CapacityUtilization: 0.85},
				"cooling":                   {RevenueGrowthYoY: 0.20, ProfitGrowthYoY: 0.22, InventoryTurnover: 5.5, CapacityUtilization: 0.80},
				"leo_satellite":             {RevenueGrowthYoY: 0.35, ProfitGrowthYoY: 0.40, InventoryTurnover: 4.5, CapacityUtilization: 0.75},
				"satellite_rf_components":   {RevenueGrowthYoY: 0.45, ProfitGrowthYoY: 0.50, InventoryTurnover: 5.0, CapacityUtilization: 0.80},
				"satellite_pcb":             {RevenueGrowthYoY: 0.30, ProfitGrowthYoY: 0.35, InventoryTurnover: 4.0, CapacityUtilization: 0.78},
				"ground_equipment":          {RevenueGrowthYoY: 0.25, ProfitGrowthYoY: 0.28, InventoryTurnover: 3.5, CapacityUtilization: 0.72},
				"laser_communication":       {RevenueGrowthYoY: 0.50, ProfitGrowthYoY: 0.55, InventoryTurnover: 3.0, CapacityUtilization: 0.70},
				"mining":                    {RevenueGrowthYoY: 0.10, ProfitGrowthYoY: 0.12, InventoryTurnover: 4.5, CapacityUtilization: 0.75},
				"precious_metals_recycling": {RevenueGrowthYoY: 0.15, ProfitGrowthYoY: 0.18, InventoryTurnover: 5.0, CapacityUtilization: 0.80},
				"copper_industry":           {RevenueGrowthYoY: 0.08, ProfitGrowthYoY: 0.10, InventoryTurnover: 4.0, CapacityUtilization: 0.72},
				"rare_earth_specialty":      {RevenueGrowthYoY: 0.05, ProfitGrowthYoY: 0.06, InventoryTurnover: 3.5, CapacityUtilization: 0.70},
				"metal_processing":          {RevenueGrowthYoY: 0.06, ProfitGrowthYoY: 0.08, InventoryTurnover: 4.5, CapacityUtilization: 0.73},
				"etf_rotation":              {RevenueGrowthYoY: 0.05, ProfitGrowthYoY: 0.05, InventoryTurnover: 0.0, CapacityUtilization: 0.0},
			},
			Rationale: "Seed bootstrap values for CycleTracker initialization; replaced by real FinMind data within 6h (auto_cycle_update). Values match the previously hardcoded defaults in initializeDefaultPositions(). Only four seed fields are configurable — RevenueGrowthYoY, ProfitGrowthYoY, InventoryTurnover, CapacityUtilization — the remaining IndustryMetrics fields (MarketCap, PE, PB, DivYield, Volatility) are set to zero and filled from market data.",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: run cmd/calibrate-seasonal --replay after accumulating 90+ days of FinMind data to replace heuristic seeds with empirically derived values",
		},
		SiliconCycle: ParameterMetadata[SiliconCycleParameters]{
			Value: SiliconCycleParameters{
				RevenueYoYThreshold:            0.15,
				BillingsYoYThreshold:           0.10,
				DRAMStabilizationThreshold:     0.0,
				BillingsStabilizationThreshold: -0.05,
				InventoryDaysThreshold:         45,
				UtilizationThreshold:           0.75,
				IndexMAPercentThreshold:        0.20,
				SOXExtremeThreshold:            0.40,
				CapexCutThreshold:              0.10,
				MinConfidence:                  0.60,
				HistoryWindowSize:              60,
			},
			Rationale: "Thresholds derived from historical TSMC revenue cycles (2015-2024), WSTS semiconductor forecast methodology, and Philadelphia SOX Index behavioral patterns. RevenueYoY=15% aligns with TSMC's average quarterly growth inflection. SOXExtreme=40% reflects the ~2σ band of SOX annual returns. CapexCut=10% is the conventional analyst threshold for 'meaningful capex reduction.'",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: backtest phase detection accuracy against labeled historical silicon cycles (e.g., 2018-2019 downturn, 2021-2022 super-cycle, 2023 inventory correction). Compare DRAMStabilizationThreshold and BillingsStabilizationThreshold against actual DRAMeXchange/WSTS data when providers are integrated.",
			Citation: &ParameterCitation{
				SourceType:       "practitioner_convention",
				SourceReference:  "TSMC quarterly reports; WSTS semiconductor forecast; Philadelphia SOX Index historical data",
				EvidenceQuality:  "medium",
				UpdatePolicy:     "review_quarterly",
				ValidationMethod: "backtest_phase_accuracy",
			},
		},
		EventSentimentCap: ParameterMetadata[float64]{
			Value:     0.05,
			Rationale: "Cap per-event sentiment adjustment at ±5% to prevent any single calendar event from dominating the composite cycle sentiment. Based on empirical observation that even major Taiwan market events (elections, MSCI rebalance, earnings season) rarely move broad market >3% in a single day, making ±5% a conservative but meaningful cap.",
			Source:    SourceHeuristic,
			Todo:      "Backtest calibration: compute distribution of actual TWSE returns during historical calendar events and set cap at the 95th percentile of excess returns.",
		},
		CompositeCard: ParameterMetadata[CompositeCardConfig]{
			Value: CompositeCardConfig{
				LayerWeights: map[string]float64{
					"silicon":        0.25,
					"business_cycle": 0.20,
					"seasonal":       0.15,
					"events":         0.15,
					"supply_chain":   0.10,
				},
				SentimentThresholds: map[string]SentimentBounds{
					"強烈看多": {Min: 1.10, Max: math.Inf(1)},
					"偏多":   {Min: 1.05, Max: 1.10},
					"中性":   {Min: 0.95, Max: 1.05},
					"偏空":   {Min: 0.90, Max: 0.95},
					"強烈看空": {Min: 0.00, Max: 0.90},
				},
				ClampMin: 0.80,
				ClampMax: 1.20,
			},
			Rationale: "Layer weights sum to 0.85 reflecting silicon-dominant Taiwan market. Sentiment thresholds calibrated to historical composite movement. Clamp [0.80,1.20] prevents extreme daily swings while allowing meaningful adjustment.",
			Source:    "heuristic; validated against 2024 TWSE daily returns",
			Todo:      "Backtest layer weights against actual forward returns from ledger data. Calibrate sentiment thresholds using historical composite coefficient distribution.",
		},
		ClassificationTree: ParameterMetadata[ClassificationTreeConfig]{
			Value: ClassificationTreeConfig{
				Segments: []IndustrySegmentConfig{
					// L1 industries
					{ID: "semiconductor", Name: "半導體產業", NameEN: "Semiconductor", Level: 1, Weight: 0.30, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2330.TW", "2303.TW", "2454.TW"}, Description: "台灣經濟支柱，包含晶圓代工、IC設計、封測"},
					{ID: "shipping", Name: "航運產業", NameEN: "Shipping & Logistics", Level: 1, Weight: 0.08, GeographicExposure: "Global", Cyclicality: "Cyclical", TechnologyIntensity: "LowTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2603.TW", "2609.TW", "2615.TW"}, Description: "受全球貿易週期影響顯著"},
					{ID: "financials", Name: "金融保險", NameEN: "Financials", Level: 1, Weight: 0.12, GeographicExposure: "Domestic", Cyclicality: "Hybrid", TechnologyIntensity: "LowTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"2881.TW", "2882.TW", "2886.TW"}, Description: "利率敏感，獲利受央行政策影響"},
					{ID: "electronics", Name: "電子零組件", NameEN: "Electronics Components", Level: 1, Weight: 0.15, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"2317.TW", "2382.TW", "2357.TW"}, Description: "連結全球科技供應鏈"},
					{ID: "ai_supply_chain", Name: "AI 供應鏈", NameEN: "AI Supply Chain", Level: 1, Weight: 0.10, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2383.TW", "3661.TW", "4938.TW"}, Description: "新興高成長領域"},
					{ID: "industrial", Name: "傳產機械", NameEN: "Industrial Machinery", Level: 1, Weight: 0.08, GeographicExposure: "Domestic", Cyclicality: "Cyclical", TechnologyIntensity: "MediumTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"1513.TW", "1590.TW"}, Description: "經濟週期後段受益者"},
					{ID: "energy", Name: "能源電力", NameEN: "Energy & Power", Level: 1, Weight: 0.05, GeographicExposure: "Domestic", Cyclicality: "Hybrid", TechnologyIntensity: "LowTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"6505.TW", "9917.TW"}, Description: "基礎設施，需求穩定"},
					{ID: "consumer", Name: "消費零售", NameEN: "Consumer Retail", Level: 1, Weight: 0.05, GeographicExposure: "Domestic", Cyclicality: "Defensive", TechnologyIntensity: "LowTech", CapitalIntensity: "LowCapital", RepresentativeStocks: []string{"2912.TW", "9927.TW"}, Description: "內需導向，經濟下行相對穩定"},
					{ID: "robotics", Name: "機器人產業", NameEN: "Robotics", Level: 1, Weight: 0.03, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2356.TW", "2049.TW"}, Description: "新興自動化領域"},
					{ID: "mining", Name: "採礦與基本金屬", NameEN: "Mining & Metals", Level: 1, Weight: 0.02, GeographicExposure: "Global", Cyclicality: "Cyclical", TechnologyIntensity: "LowTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"1605.TW", "1707.TW"}, Description: "大宗商品週期"},
					{ID: "leo_satellite", Name: "低軌衛星", NameEN: "LEO Satellite", Level: 1, Weight: 0.02, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"6271.TW", "3426.TW"}, Description: "衛星通訊新興供應鏈"},
					{ID: "etf_rotation", Name: "ETF 輪動", NameEN: "ETF Rotation", Level: 1, Weight: 0.00, GeographicExposure: "Domestic", Cyclicality: "Hybrid", TechnologyIntensity: "LowTech", CapitalIntensity: "LowCapital", RepresentativeStocks: []string{}, Description: "跨產業策略配置"},
					// Semiconductor L2
					{ID: "foundry", Name: "晶圓代工", NameEN: "Foundry", Level: 2, ParentID: "semiconductor", Weight: 0.50, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2330.TW", "2303.TW"}, Description: "TSMC, UMC"},
					{ID: "server_assembly", Name: "伺服器組裝", NameEN: "Server Assembly", Level: 2, ParentID: "semiconductor", Weight: 0.25, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2324.TW", "2356.TW"}, Description: "AI server assembly"},
					{ID: "cooling", Name: "散熱方案", NameEN: "Cooling Solutions", Level: 2, ParentID: "semiconductor", Weight: 0.25, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"3324.TW", "6230.TW"}, Description: "Liquid/air cooling"},
					// Mining L2
					{ID: "precious_metals_recycling", Name: "貴金屬回收", NameEN: "Precious Metals Recycling", Level: 2, ParentID: "mining", Weight: 0.30, GeographicExposure: "Global", Cyclicality: "Cyclical", TechnologyIntensity: "MediumTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"3550.TW", "8936.TW"}, Description: "Gold/silver recovery"},
					{ID: "copper_industry", Name: "銅工業", NameEN: "Copper Industry", Level: 2, ParentID: "mining", Weight: 0.25, GeographicExposure: "Global", Cyclicality: "Cyclical", TechnologyIntensity: "LowTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"1605.TW", "8930.TW"}, Description: "Copper mining/refining"},
					{ID: "rare_earth_specialty", Name: "稀土及特殊材料", NameEN: "Rare Earth & Specialty", Level: 2, ParentID: "mining", Weight: 0.20, GeographicExposure: "Global", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2031.TW", "1815.TW"}, Description: "Rare earth elements"},
					{ID: "metal_processing", Name: "金屬加工", NameEN: "Metal Processing", Level: 2, ParentID: "mining", Weight: 0.25, GeographicExposure: "Domestic", Cyclicality: "Cyclical", TechnologyIntensity: "LowTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"2015.TW", "5007.TW"}, Description: "Metal fabrication"},
					// LEO Satellite L2
					{ID: "satellite_rf_components", Name: "衛星射頻元件", NameEN: "Satellite RF Components", Level: 2, ParentID: "leo_satellite", Weight: 0.35, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"6271.TW", "4958.TW"}, Description: "RF front-end modules"},
					{ID: "satellite_pcb", Name: "衛星用 PCB", NameEN: "Satellite PCB", Level: 2, ParentID: "leo_satellite", Weight: 0.25, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "MediumCapital", RepresentativeStocks: []string{"2355.TW", "8046.TW"}, Description: "High-frequency PCB"},
					{ID: "ground_equipment", Name: "地面設備", NameEN: "Ground Equipment", Level: 2, ParentID: "leo_satellite", Weight: 0.25, GeographicExposure: "Domestic", Cyclicality: "Cyclical", TechnologyIntensity: "MediumTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"2314.TW", "2353.TW"}, Description: "Ground stations & terminals"},
					{ID: "laser_communication", Name: "雷射通訊", NameEN: "Laser Communication", Level: 2, ParentID: "leo_satellite", Weight: 0.15, GeographicExposure: "Export", Cyclicality: "Cyclical", TechnologyIntensity: "HighTech", CapitalIntensity: "HighCapital", RepresentativeStocks: []string{"3426.TW", "6533.TW"}, Description: "Optical inter-satellite links"},
				},
			},
			Rationale: "Complete industry classification hierarchy migrated from hardcoded types.go to ParametersConfig. L1 weights sum to 1.0, L2 weights within each parent sum to 1.0. Representative stocks and attributes serve as initialization seeds; auto_tree_update pipeline refreshes weights quarterly from market-cap data.",
			Source:    "heuristic",
			Todo:      "Auto-update: run cmd/backfill-industry-tree after each quarter close to recompute weights from TWSE market cap data. Validate: ensure L1 weights sum to 1.0 and L2 weights per parent sum to 1.0.",
		},
	}
}

func defaultNarrativeConvictionParameters() NarrativeConvictionParameters {
	return NarrativeConvictionParameters{
		ThemeHitRates: ParameterMetadata[map[string]float64]{
			Value: map[string]float64{
				"AI_capex_surge":          0.81,
				"US_rates_up":             0.72,
				"JPY_carry_unwind":        0.68,
				"geopolitical_risk_spike": 0.65,
				"oil_price_shock":         0.58,
			},
			Rationale: "Historical hit rates for narrative themes; AI_capex_surge highest (0.81), oil_price_shock lowest (0.58) due to TW semiconductor hedging",
			Source:    SourceHeuristic,
			Todo:      "Calibrate: derive from 36-month narrative event backtest",
		},
		SkillToTheme: ParameterMetadata[map[string]string]{
			Value: map[string]string{
				"semiconductor_desk":   "AI_capex_surge",
				"ai_supply_chain_desk": "AI_capex_surge",
				"shipping_desk":        "oil_price_shock",
				"financials_desk":      "US_rates_up",
				"etf_rotation_desk":    "JPY_carry_unwind",
				"value_yield":          "US_rates_up",
				"earnings_quality":     "AI_capex_surge",
				"growth_momentum":      "AI_capex_surge",
				"technical_breakout":   "AI_capex_surge",
			},
			Rationale: "Maps agent skills to narrative themes; semiconductor/ai_supply_chain/earnings/growth/technical → AI_capex_surge, financials/value_yield → US_rates_up, etf_rotation → JPY_carry_unwind, shipping → oil_price_shock; aligns with narrative_conviction_modulator.go defaultSkillToTheme",
			Source:    SourceHeuristic,
			Todo:      "Validate: review agent-narrative alignment with domain experts",
		},
	}
}
